### ISSUE TITLE
MOF version of abstract syntax

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#10]
preferably, automatically generate the MOF version from the EBNF.

**Comment by tillmo** [comment]
@conradbock says: OMG might ask if you've run the XMI through OMG's validator (http://validator.omg.org/se-interop). It gives a lot of spurious errors, I've heard. You could do your best with validation, submit it, and ask OMG/Peter Denno about particular errors before the meeting. Usually Pete Rivett will check it a few days before the meeting, and you can post updates.

**Comment by MGlauer** [comment]
The XMI files has been adapted to run through the validator without any general errors left. I think this issue can be closed.

**Comment by tillmo** [comment]
today, I needed to commit one slight change of the abstract syntax. Could you please have a look?

**Comment by MGlauer** [comment]
Adapted XMIs and pictures accordingly. Hope it did not do something hazardous to any designs
