### ISSUE TITLE
explain extensions versus unions

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#100]
explain: extensions for small additions, unions for sums of large OMS

**Comment by fabianneuhaus** [comment]
do you have a particular section in mind, where I should include this?

**Comment by tillmo** [comment]
I think 9.4 would be well-suited.

**Comment by fabianneuhaus** [comment]
I added the following: 
(the major difference between a union and extension is that the members of the unions need to be self-contained OMS, while the extensions may reuse the signature of the extended OMS)
If you approve, please close the ticket.
