### ISSUE TITLE
anything relevant in Christoph's old issues?

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#103]
14) Is there any reasonable “implied default” for correspondences?  (Yes, the "alignment API" equivalence) - Christoph
43) The following listings are actually not EBNF according to its definition – adapt them! - Christoph 
65) Requirement for prefix maps needs to be rephrased to take into account DOL XML or any XML serialization of DOL RDF, which allow prefix maps everywhere. - Christoph
79) Properly integrate this text from our LaRC 2011 paper - annotations? - Christoph
88.1) fix XML conformance of serializations: attributes/child-elements from other namespaces are not necessary, but @ xml:id is essential, so that we can assign IDs to anything (e.g. to axioms) – Christoph
      update of 2013-06-11: XML and RDF conformance actually allow the same level of "annotatability" in terms of ID injection
89a) we want to use the comments in ontology languages for a "soft intrusion", e.g. for recording names of axioms and proof goals.
105) maybe we need to say something about encoding IRIs as URIs in the ASCII case - Christoph
xxx) clean up standard by deleting references to XML and RDF serialisations of DOL - Christoph
113) Provide linear syntax here (as in the paper) - Christoph
xx1) complete DOL RDF vocabulary for registry - Christoph
202) we will consider simplifying the terminology section on annotations and remove the terms datatype and literal, because they are actually not necessary for specifying DOL's annotation support. Use RDF or RDFa for annotating DOL text syntax - Christoph
203) remove the term XML schema and check whether we need the term standoff markup (see also US comment referencing 203 below)- Christoph
204) Relations present in Lola should become notes in the terms section of the WD (e.g. language supports logic). - Christoph
304) US reference section 5.2, but the issue really transcends specific sections. It is this: it’s unclear to me what the nature of annotation is in this standard. E.g., in section Introduction, it is stated that “DOL’s modularity and annotation constructs can either be embedded into existing ontologies as non-disruptive annotations, or they can be provided as standoff markup, pointing to the ontologies they talk about; DOL specifies a syntax and semantics for both variants. DOL’s modularity constructs are semantically well-founded within a library of formal relationships between the logics underlying the different supported ontology languages.” Is annotation symbolic, i.e., interpretable itself in DOL, or does DOL add uninterpreted strings, i.e., documentation, to ontologies? (--lo) Response: Annotations are uninterpreted. Possible remaining uses of the term "annotation" in a semantic context (e.g. conservative extensions) will be removed. We are no longer going to embed annotations into existing ontologies. Christoph -- Action: Annotation is important on ontology engineering, and DOL _enables_ annotations (by giving IRIs to symbols, and injecting IDs) and comments, but annotation itself will be left to external mechanisms such as RDF.  Remove/rephrase "annotation" wherever it occurs, including the Introduction paragraph mentioned.
420) Maria-17-2 Christoph
Can we really get by with using just the other annotation vocabularies? E.g., I'm quite sure I'd want to annotate declared links. How would I be able to do that?
Reply
Annotating a declared link will be possible by giving the link an IRI. But then, any semantically meaningful annotation (other than just a source code comment) needs to have an RDF semantics, and therefore a predicate/property. As so many suitable properties exist already, we do not intend to reinvent any within DOL.
Action: remove "annotation vocabularies" annex, get rid of other occurrences of "annotation vocabularies" (as anything beyond _enabling_ annotation is no longer DOL's business). - Christoph
501) new on 2013-04-17: change "projection" into "approximation".  New syntax: ONTO approximate in LOGIC with METHOD (where METHOD is an IRI, as with translation)

69a) The DIST-ONTO-NAME is an IRI that should (as a good practise, but not enforced) agree with the IRI of the document. Indeed, this applies to any usage of IRI in the standard. This should be stated in the standard - Christoph
77) DOL Serializations: Essential points are: - need to be able to say: “the file at URL U is in OWL 2 Manchester syntax”, - maybe use packaging/wrapping format, - compare MIME types, HTTP content negotiation (but don’t go too deep into communication protocols) -  Christoph
78) MERGED INTO 77, 2012-09-26.  Maybe we can implement something like the Linux command “file”? - Christoph
89) what if an ontology language does not support IRIs? e.g. OWL doesn’t specify IRIs for import declarations, so we can, e.g., not annotate them when using the RDF serialization of OWL. We could only do it via RDF reification, or by using an XML serialization. Invent new language construct. - Christoph
502) new on 2013-05-15: re section "DOL serializations": provide two complementary _concrete_ (!) syntax constructs for escaping (in case a serialization conflicts with one of them).
503) move (77) to a more appropriate subclause within abstract syntax clause

**Comment by clange** [comment]
BTW in yesterday's work I actually addressed those of the above that were still relevant.
