### ISSUE TITLE
Upload modelling examples from Appendix I to ontohub.org

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#115]

**Comment by katragaddarajendra** [comment]
I had uploaded all the examples to 'dol-examples' repository.Some of the files are unable to open. I tried to fix the errors. But still except the files concept.dol,alignment.dol,minimize.dol,none are working. When I try to create the files algebra.dol and distributed.dol on Microsoft word or notepad by copying the contents from 'ebnf-OMG_OntoIOp_current.pdf', there are certain characters such as '\stackrel' which are not supported by text editors. I am able to add very few of them manually.Please have a look at the failed files.

**Comment by tillmo** [comment]
Could you please copy the examples from the LaTeX source at https://raw.githubusercontent.com/tillmo/DOL/master/Standard/OMG_OntoIOp_current.tex

**Comment by katragaddarajendra** [comment]
I tried to do that already. As I cannot create a file directly on Ontohub, I have to copy the contents from above tex file to any text editor [ But text editors like Ms Word, Notepad and sublime does not support characters such as \stackrel ] and then make it as .dol file.

**Comment by katragaddarajendra** [comment]
Successfully uploaded all the examples to https://ontohub.org/dol-examples. Please have a look and close the issue.

**Comment by tillmo** [comment]
Looks good, but please also integrate the latest changes of the LaTeX document.

**Comment by katragaddarajendra** [comment]
I had updated with latest changes.Could you please check.

**Comment by tillmo** [comment]
Many thanks! In the meantime, a number of examples have been added in section 7. Could you please also upload these?

**Comment by katragaddarajendra** [comment]
I had updated with examples from Section 7. Could you please check.
