### ISSUE TITLE
Approval for change

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#118]
I removed in 2.1: 
"\footnote{Institutions are necessarily monotonic; conformance criteria for non-monotonic logics are still under development. However, minimization provides non-monotonic reasoning in DOL. It is also possible to include non-monotonic logics by construing entailments between formulas as sentences of the institution.} "
In my opinion, this kind of discussion footnotes don't really have a place in a standards document. In particular not into the conformance section.

**Comment by tillmo** [comment]
In section 0, we say: "Proposals may provide constructs for non-monotonic logics. - Currently, only monotonic logics are supported." I wanted to have this also in the main part. Maybe include it in the main text, not in a footnote.

**Comment by fabianneuhaus** [comment]
I still think that the conformance section is a weird place for this. I would suggest that this should be within the scope section: non-monotonic logics are out of scope, because they do not meet our conformance criteria. (And there one may add a footnote about the possibility to mimic non-monotonic behaviour, ideally with reference to an example in the appendix.)
