### ISSUE TITLE
cryptic text

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#119]
from section 2.1.1 
"A language translation is conforming with DOL if it is a mapping
between the abstract syntaxes that restricts to a conforming logic
translation when restricted to the logical language aspect."

As far as I can tell, it is not explained what "restring to a conforming logic translation" means. It is also unclear what "restricting to the logical language aspect" means. Together this makes the text cryptic. 
Please reformulate.

**Comment by tillmo** [comment]
better now?

**Comment by fabianneuhaus** [comment]
yes, better. However, I don't think that most readers will know what "diagram ... commutes" means. Is there a less formal way to express it or a reference we can use to clarify? 

BTW I changed "(co)comorphism" to "(co)morphism" -- assuming that this was a typo

**Comment by tillmo** [comment]
better now?

**Comment by fabianneuhaus** [comment]
great!
