### ISSUE TITLE
DOL conformant application

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#122]
I noticed that a tool that section 2.4 does not say anything about reading DOL files. 
What about a tool that only reads DOL files? E.g., a theorem prover, which supports heterogenous reasoning and provides as output only proofs.  Wouldn't it be -- in some other way -- be conferment to DOL?

**Comment by tillmo** [comment]
do you mean 2.5.? 2.4. does not mention tools.

**Comment by fabianneuhaus** [comment]
yes, 2.5

**Comment by tillmo** [comment]
OK, have added that Hets is the reference implementation.
