### ISSUE TITLE
Latex errors

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#124]
I get multiple errors when compiling. This has been going on for a while now. 

Processing: tikz.code.tex
Latex Error: /usr/local/texlive/2014/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarymatrix.code.tex:22 LaTeX Error: Missing \begin{document}.

Latex Error: /usr/local/texlive/2014/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarymatrix.code.tex:22 Too many }'s.

Latex Error: /usr/local/texlive/2014/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarymatrix.code.tex:22 Too many }'s.

Processing: tikzlibraryarrows.code.tex
Latex Error: ./OMG_OntoIOp_current.tex:94 Extra \fi.
Latex Error: ./OMG_OntoIOp_current.tex:94 Extra \fi.

Processing: illustrations/DOL-tikz-preamble.tex
LaTeX Warning: Label `c:keywords' multiply defined.

LaTeX Warning: Label `CommonLogic' multiply defined.

Including: omglogo.jpeg
Latex Error: ./OMG_OntoIOp_current.tex:1167 LaTeX Error: Float(s) lost.
Latex Error: ./OMG_OntoIOp_current.tex:1622 Missing } inserted.

**Comment by tillmo** [comment]
I cannot reproduce the first five errors. And I have fixed the last two errors.

**Comment by tillmo** [comment]
works for me
