### ISSUE TITLE
Is there a difference between basic OMS language and OMS language?

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#126]
I don't think so. But I wanted to make sure before I delete all "basics" in "basic OMS language"

**Comment by tillmo** [comment]
there is a difference, see 4.7: OMS languages can have a structuring language aspect. E.g. OWL has (minimal) structuring constructs such as imports.

**Comment by fabianneuhaus** [comment]
Ok. I'll add this to the "Terms and Definitions" section then

**Comment by fabianneuhaus** [comment]
Searching through the PDF I found 5 occurrences of "basic OMS language". I am fairly confident that in all cases we just mean "OMS language". The contexts are:  
- CURIEs that have a prefix may not be acceptable identifiers in every serialization of a
basic OMS language
- Term =  <an expression specific to a basic OMS language> 
- Sentence = <an expression specific to a basic OMS language> 
- While DOL uses IRIs as identifiers throughout, basic OMS languages do not necessarily do; for example:
- CURIEs that have a prefix may not be acceptable identifiers in every serialization of a basic OMS language

Please let me know whether you agree. If so, I'll remove the "basic"

**Comment by tillmo** [comment]
For items 1,4 and 5 I agree. For 2 and 3 it is debatable, because terms and sentences are part of basic OMS (there might also be terms formed of structuring operations, but these are not meant here). So for items 2 and 3, I rather would keep "basic OMS language".

**Comment by fabianneuhaus** [comment]
I don't understand your argument. At least not given the definition of "basic OMS" that I thought we agreed on. 
"basic OMS"  = "A native OMS that does not utilize any elements from the structuring language aspects of its language." 
You are right that OMS occur in basic OMS, but they can also occur in native OMS that are structured OMS (e.g., an OWL ontology with importation). 
 
By the way, we do currently have no definition of "basic OMS language". It seems to me that 
"OMS language with an empty structuring language aspect" would be the most obvious definition. But again, in this case  the definition would make no sense, since "term" should be defined for any OMS language.

**Comment by fabianneuhaus** [comment]
note: I removed the occurrences 1,4,5.

**Comment by tillmo** [comment]
I do not understand your argument either. Terms and sentences usually occur in basic OMS, e.g. in a CL formula, and not in in a cl-import.
I am fine with removing the "basic" if we do not have a definition of "basic OMS language", However, "basic OMS language" occurs a number of times in the document. We definitely have the "logical language aspect of an OMS language", and it should be synonymous to (but probably more precise than) "basic OMS language".

**Comment by fabianneuhaus** [comment]
ok. if you use "basic OMS language" as a synonym for "logic language aspect of an OMS language", then I understand you. This wasn't how I understood it, I understood it as "language that has no structuring language aspect".  
My proposal is: 
- we do not introduce this synonym, because synonyms just make the document harder to read. 
- we change the rule in the abstract syntax to 
Term = an expression specific to an OMS language
- we add a note to terms and definition entry, which says 
"Note: A term belongs to the logic language aspect."

**Comment by tillmo** [comment]
agreed
