### ISSUE TITLE
Refer to community URL for registry

### ISSUE THREAD

**Issue by clange** [tillmo/DOL#129]
Try purl.org

**Comment by tillmo** [comment]
currently, we mention ontohub.org (which will actually host the registry). Probably you suggest to use purl.org/DOL? What about logichub.org? (it already points to ontohub.org...)

**Comment by tillmo** [comment]
we take logichub.org

**Comment by clange** [comment]
Let's see how well replying to these mails works (have limited Internet
right now). Logichub is fine with me, except that purl is more
future-proof. If some day you want to change from logichub to
whateverelsehub you'd simply have to reconfigure the purl redirect.

-- 
Christoph Lange(-Bever)
http://langec.wordpress.com/about
Sent from a mobile device; please excuse my brevity.
