### ISSUE TITLE
Old TikZ/PGF files in the Standard directory cause compilation bug

### ISSUE THREAD

**Issue by clange** [tillmo/DOL#131]
A long time ago I had put static copies of the, then, latest version of TikZ/PGF into the Standard directory. Now, they make it impossible to compile the latest LaTeX source of the standard.

For you too?

TikZ/PGF is no longer as exotic as it used to be; in fact it should be part of every reasonable TeX installation.

If all of us have it, we could delete all `pgf*` files and all `tikz*` files except `tikz-uml.sty`.

**Comment by tillmo** [comment]
it seems that @fabianneuhaus has a similar problem, see #124. I myself do not encounter the problem. But I have TikZ/PGF...
