### ISSUE TITLE
simplified semantics of associations in UML class diagrams

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#132]
Currently, the semantics of an association is a sequence of tuples. From this sequence of tuples, the semantics of the association ends is derived, possibly using abstractions to sets, bags or ordered sets.

I have several questions to @AlexanderKnapp:
1. You write "Ignoring the annotations τ_i in the interpretation of an association is intentional, see the semantics of associations in the UML Superstructure Specification 2.4.1, p. 37" - agreed, but then why have the τ_i at all? Can't we remove them from associations in signatures? And just keep them in the association ends? Ah, I just see that it seems that the association end declarations are part of the association declaration... So forget about this point...
2. The translation to Common Logic is complicated by the sequence semantics for associations. If all member ends have default annotations (i.e. unordered, unique), could we then define the semantics to be a *set* of tuples?
3. An even more radical solution: we could define the semantics of an association *always* as a set of tuples. In case one end is ordered or not unique, we assume that a model interprets this association end as a function into bags, sequences or ordered pairs. Note that this interpretation of the association end is an *extra component* of the model, and not derived from the semantics of the association (as it is currently). But of course, we need a compatibility condition between the interpretation of the association and that of the end, namely that for a given x, for all elements y \in semantics(assoc end)(x), we have that (x,y) is a tuple in the association.
I think that these considerations could simplify things considerably. 
Of course, we have to make sure that we still are in accordance with OMG UML version 2.5 (ptc/2013-09-05), section 11.5.3: "When one or more ends of the Association have isUnique =false, it is possible to have several links associating the same set of instances. In such a case, links carry an additional identifier apart from their end values. When one or more ends of the Association are ordered, links carry ordering information in addition to their end values."

**Comment by AlexanderKnapp** [comment]
Would it simplify matters if we replace the sequences of tuples by sets of tuples with an additional ordering component?

**Comment by tillmo** [comment]
no, I do not think so.
I think item 2 above would already be a good simpliication. Item 3 is debatable, since it deviates much from the standard, which expicilty says that the semantics of the association carries ordering information. (Item 1 is a wroing idea anyway)

**Comment by tillmo** [comment]
OK, I have now implemented item 2, see df24dbe
