### ISSUE TITLE
update references to UML standard from 2.4.1 to 2.5

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#133]

**Comment by tillmo** [comment]
@AlexanderKnapp, could you possibly do this? Conrad wants to have references to version 2.5. Alternatively, we could keep the references to 2.4 as well.

**Comment by AlexanderKnapp** [comment]
I've added the references to UML 2.5, but kept the references to UML 2.4.1.

**Comment by tillmo** [comment]
excellent!
