### ISSUE TITLE
hopefully just a typo

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#134]
It says in section 9.4: 
"the application of a substitution to a sentence." 
I assume this should be 
"the application of a substitution to an OMS"

**Comment by tillmo** [comment]
no, this is not a typo. Substitutions can be applied to sentences. However, we could extend this to basic OMS, if you are more comfortable with that.

**Comment by fabianneuhaus** [comment]
the abstract grammar says that I can apply substitutions to OMS
