### ISSUE TITLE
more terminological troubles

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#135]
this is linked to #100 
it seems that we have a third notion of "basic OMS" (beyond native). The difference is more subtle though.   The definition in the section 4 is 
"basic OMS: a signature equipped with a set of sentences and annotations, which may be used as a building block for a larger OMS." 
Note that it does not say that the basic OMS needs to be conform to the OMS language. This is because basic OMS may be the snippets, which are used in extending an OMS. These may not conform to the syntax rules of the language, because the signature is not fully declared in the snippet. For example
Class: Foo SubClassOf: Bar 
would be such a basicOMS. 
However, according to the grammar every basic OMS is an OMS, and can be, for example, used in unions. As far as I know, this should not be possible for an 'incomplete' OMS like
Class: Foo SubClassOf: Bar

**Comment by tillmo** [comment]
yes, that is true. But this subtle difference is handeled by the semantics, see 11.2: "We moreover assume similar language-specific semantics of a basic OMS fragment $O$ in the context of previous declarations, denoted $sem^{(\Sigma,\cM,\Delta)}_L(O)$." I would not introduce the distinction between "basic OMS" and "basic OMS fragment" in the syntax, but rather subsume both under "basic OMS".

**Comment by fabianneuhaus** [comment]
ok
