### ISSUE TITLE
add native OMS to grammar

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#136]
Given that BasicOMS now means OMS without structuring aspects (e.g., no importations), an OWL with importation is not not an basic OMS. Thus, given the current grammar, an that ontology is not an OMS!

**Comment by fabianneuhaus** [comment]
depending on how this issue is fixed, we need to adjust point 6.5.2(c) in table 0.1

**Comment by fabianneuhaus** [comment]
we need a term for "OMS written in DOL". So far we have been using "structured OMS". E.g. in: 
" Native OMS inherit their semantics from the underlying OMS languages. Structured OMS,  OMS mappings, and OMS networks have a declarative model-theoretic semantics, which is  defined in \cref{c:semantics}. "
However, this is misleading, since some structured OMS are native OMS.

**Comment by tillmo** [comment]
Concerning your first point: an OWL ontology with importation will be stored under some IRI, and then it can be referenced via (in terms of abstract syntax) `oms-ref IRI`, which is an OMS.
Concerning the second point: I suggest to use "DOL structured OMS" versus "native structured OMS".
