### ISSUE TITLE
Is this really true?

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#137]
From a note in the term and definition section : 
"An OMS has a single signature and model class over that signature as its model-theoretic semantics."

I understand that this is true for native OMS or flattenable OMS. But what about the union of OMS that are written in two arbitrary logics? And I thought that the semantics of a library is a graph?

**Comment by tillmo** [comment]
this is true. See this paper http://www.informatik.uni-bremen.de/~till/papers/disthet.pdf on p.2. Our OMS are what is called there "focused heterogeneous specifications", and our networks are what is called there "distributed heterogeneous specification".

**Comment by fabianneuhaus** [comment]
thanks, I just wanted to make sure.
