### ISSUE TITLE
Question concerning the semantics of non-basic native OMS

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#138]
We write
"Since institutions allow the differences between OMS languages to be elided to common abstractions, the semantics of basic OMS is presented in a uniform way. The semantics of structured OMS, OMS mappings, OMS networks, and other DOL expressions is defined using model-theoretic constructions on top of institutions."
How does that work in the case of CL vers. 2, where the importations are wrapped into the model theoretic semantics (and, thus, presumably in the institutions)?

**Comment by tillmo** [comment]
CL documents with importations are native OMS, like OWL documents with importations. The peculiarity of CL is that you can have an importation as part of a sentence, which is in turn part of a "basic OMS" (which then is not really "basic"). We could allow or forbid this in DOL. (If we forbade this CL feature in basic OMS, you could still use it in native OMS.)
