### ISSUE TITLE
Question concerning name spaces

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#139]
"[namespace] an IRI that identifies the complete OMS (a \emph{basic OMS} in DOL terminology)"

I suggest to rewrite this as
"an IRI that identifies the a native OMS" 
or, since I don't see a reason, why dol oms shouldn't get their name spaces, even just as 
"an IRI that identifies the a OMS" 
Do you concur with either?

**Comment by tillmo** [comment]
yes (but "the a" is a typo). Could you also add an ednote that this should be checked against annex M?
