### ISSUE TITLE
weak definitional extension, implied extension 

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#143]
Following my task of simplifying the terminology: I seems to me that we do not use "weak def extension" and "implied extension" in the standard. Thus, there is no reason to introduce the terminology. Shall we remove them from the term definition section?

**Comment by tillmo** [comment]
in 9.4. we say "an extension of an OMS with a basic or a minimizable OMS, optionally named and/or marked as conservative, monomorphic, definitional, weakly definitional or implied," So we should keep the terms.
