### ISSUE TITLE
Smaller OMS language? 

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#144]
from section 4.5: 
"**approximant** approximation (in the sense of a logically implied theory, possibly after suit- able translation) of an OMS in a smaller signature or OMS language."
The latter ("OMS in a smaller [] OMS language") is weird. 
Do you mean "or in a less expressive OMS language"? Shall I change that?

**Comment by fabianneuhaus** [comment]
note that the same question arises w.r.t
maximum approximant

**Comment by tillmo** [comment]
I think "OMS sublanguage" is meant (not any less expressive language is a sublanguage). Please change it.
