### ISSUE TITLE
Seemingly inconsistent treatment of reduction

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#146]
In the terms and definition section "reduction" is discussed under the heading OMS mapping. 
However, both in the abstract and the concrete syntax the syntactical category "reduction" is a kind of OMS. 
Now, it seems to me that there is a systematic ambiguity for reduction and similar operations. The operation is applied to an existing OMS A and yields a new OMS B. In one sense OMS B is a reduction. In another sense, the reduction is the relationship between A and B. We probably should make that connection explicit. 
But be this as it may, the way it is right now is confusing, because it looks inconsistent.

**Comment by tillmo** [comment]
I suggest to move "renaming" and "reduction" from the section "OMS mappings" to "structured OMS".

**Comment by fabianneuhaus** [comment]
what about 
(a) union
(b) combination
(c) importation
The first two are syntactic subcategories of "OMS", and (c) is basically the result of an OMS reference, isn't it?

**Comment by tillmo** [comment]
agreed
