### ISSUE TITLE
Confusing note

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#148]
" The opposite of an OMS network is an \termref{OMS}, which
 focuses on the specification of a single \termref{logical theory}."

I find this note confusing, because I don't know what "opposite" is supposed to mean. It seems that something similar as distinction between "structured OMS" and "basic OMS" is intended here? I suggest to either rephrase it or remove the note.

**Comment by tillmo** [comment]
have rephrased it
