### ISSUE TITLE
informative annexes? 

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#153]
I have made all annexes informative. I think we agreed that the conformance of the various languages to OMS should be informative (this was in the context of the UML class diagram discussion). 
However, I am not entirely sure whether we want the RDF vocabulary in Annex A to be normative. If you want me to change it back, just assign the issue back to me, otherwise please close it.

**Comment by tillmo** [comment]
yes, annex A should be normative. All the others informative.

**Comment by fabianneuhaus** [comment]
ok.
