### ISSUE TITLE
status of dia5.png

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#157]
dia5.png in section L.5. OMS Mappings
That seems weird to me, since it does not seem to be an OMS mapping. Maybe it should get its own subsection?

More importantly, I have been using the headings of the sections as descriptions for the submission inventory document. So, even if it stays in the same section, I'll need some short description of its role.

**Comment by tillmo** [comment]
dia5.png specifies "Double", which is used in dia4.png (which is about diagrams). So dia5.png contains auxiliary stuff for mappings. I think it could even be merged into dia4.png.

**Comment by tillmo** [comment]
or even easier: just omit dia5.png. "Double" does not need specification.
