### ISSUE TITLE
Revise DOL ontology

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#165]
* each term (class, object property, data property) needs to be annotated with a natural language explanation (preferably taken or adapted from the terms and definitions section)
* ~~each term should be sufficiently axiomatized~~ I think we did as much as can be done in OWL; for things beyond OWL see the "developers' notes"
* imported terms should be axiomatized, either by importing the referenced ontology (only for standardized ontologies!), or by axiomatizing the term from scratch
* ideally, the list of terms in the ontology should coincide with that in chapter 4  
* tables A.1 and A.2 should give an overview of the whole ontology, not only of the LoLa part (not sure whether this means that all terms should be listed in the table, though)

**Comment by tillmo** [comment]
Here are the comments by Pete Rivett, most of them have already been fixed:
* This is an OWL file in RDF/XML format.
* This is a substantial ontology yet is not well-documente din the spec document.
* Though the Inventory lists no dependencies there are in fact many including OMG’s Specificationmetadata, Dublin Core, SKOS
* Ironically it does what the specification says should not be done: declare a default URL (xml:base). This is not only declared but made use of e.g. line 378 has “strictlyStrongerThan” with no explicit namespace
* The URI for the ontology inside the file is not an OMG one but  https://ontohub.org/meta/lola/ontology which is inconsistent with the Inventory
* The ontology includes: Copyright (c) 2014 Athan Services which is not a declared copyright holder in the specification document.
* Also there are elements which have a <creator> property with value  Christoph Lange – does he work for a declared copyright holder?
* Several of the comments in the ontology refer to it as “OntoIOp specification” whereas the specification itself consistently uses only DOL to name the spec (OntoIOP is the RFP only)
* There are several ontology elements declared in the namespace http://example.org/todo# which seems to indicate that it’s not complete? Also questions such as “I don&apos;t think we need subclasses for specific types of mappings, do we?”
* Some elements e.g. hasAlignment seem inconsistent – no rdfs:label and it uses rdfs:comment rather than skos:definition which the others use

**Comment by tillmo** [comment]
the current version can be found (and edited) at https://ontohub.org/meta/lola/ontology/lola.omn

**Comment by clange** [comment]
I am now working on a file downloaded from https://ontohub.org/meta/lola/ontology/lola.omn and will make it available to you once done. No longer under the name LoLa though, as discussed in #196.

**Comment by clange** [comment]
I think this issue can be closed. Actually all _these_ revisions to the ontology have been made in the meantime. It seems that at the September OMG meeting no further issues about the ontology came up.
