### ISSUE TITLE
add translation of UML class diagrams to OWL

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#166]

**Comment by MGlauer** [comment]
@tillmo Do you need the UML-CDs translated to OWL-files or is some formal description of the process required? The issue topic sounds like the latter one, but I don't think that is what you intended.

**Comment by tillmo** [comment]
In annex H, a new subsection with a translation should be added. There is already a lot of literature about such translations, so a translation from the literature could be used.

**Comment by MGlauer** [comment]
I added a possible translation enclosed in \cbs ... \cbe. 
I did not find a translation that allows operations or associations with more than two ends, though. I believe I can think of a rather technical workaround for the first one, but that would require more elaboration time than we got atm.

**Comment by tillmo** [comment]
good! We should discuss whether we want to use RDF syntax here, or prefer Manchester syntax.

**Comment by MGlauer** [comment]
I prefer the RDF, because it is much easier to read. But I will rewrite it, if you prefer Manchester syntax.

**Comment by clange** [comment]
Excuse me for chiming in, but

1. I believe most people in the DOL team would consider Manchester syntax most readable
1. The current draft mixes two different XML syntaxes for OWL, one being RDF/XML, the other one being OWL XML (all snippets that use owl:SubClassOf).

**Comment by MGlauer** [comment]
Ok, I revised the translation and changed everything to manchester syntax.
