### ISSUE TITLE
Reference a standard for linked data principles

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#197]
Comment from Pete Rivett: Section 2.3 mentions, but does not reference a standard for “linked data principles”.

**Comment by clange** [comment]
The de facto authoritative reference for "linked data" (http://www.w3.org/DesignIssues/LinkedData.html) is not formally a standard; however there is now a W3C Recommendation for the [Linked Data Platform](http://www.w3.org/TR/ldp/). It also mentions the key principles, so I cited this one in commit b7364a65878ad36c2508a09d860aa9811f439a8d.

I also updated the terminology section 4.3 accordingly.
