### ISSUE TITLE
Need PDF to do general proofreading

### ISSUE THREAD

**Issue by longstreth** [tillmo/DOL#198]

**Comment by tillmo** [comment]
sure, we will provide a PDF. Would it be OK to provide it on June 29, and you giving feedback on June 30th?

**Comment by longstreth** [comment]
OK, but an extra day or two would be better.  It would be a particular help if you can shoot me an early galley in time for me to work on it over the weekend (to my email: longstreth@acm.org)

**Comment by tillmo** [comment]
OK, will do so

**Comment by tillmo** [comment]
The PDF should be sent on the evening of July 4.

**Comment by tillmo** [comment]
see https://github.com/tillmo
