### ISSUE TITLE
Review Annex B

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#205]
Currently, most of annex B seems rather shaky to me. The Annex contains the sentence "OWL can be formalized as institution as follows" and then there follows a long definition -- indeed the definition covers most of the section. However, most of that text discusses the variants of OWL. I don't see how that would establish the institution.

**Comment by tillmo** [comment]
The definition first introduces an institution for ALC. All components of the institution are introduced (although only very briefly, while details can be found in the literature). Then, this institution is extended to sROIQ, which is the logic of OWL. Then, some restrictions are introduces, covering the profiles of OWL. I do not see what should be missing.

**Comment by fabianneuhaus** [comment]
I expected that we need to discuss the model theory of OWL. Which is more complicated than sroiq, let alone ALC, since it contains all kind of weird stuff. E.g., datatypes and facets.
http://www.w3.org/TR/owl2-direct-semantics/
