### ISSUE TITLE
Does the "kind of extension" apply to the extending ontology, or to the extension relation between two ontologies?

### ISSUE THREAD

**Issue by clange** [tillmo/DOL#207]
A question re. the `extends` property in the DOL Ontology:

While the abstract and text syntaxes of DOL attach the 'kind of extension' to _one_ ontology, the semantics (CASL reference section 5.2.5) rather suggests that this is a relation between _two_ OMS (which may or may not be given explicitly in the syntax).  Is it, therefore, OK, to model `extends` as an object property, and to have a hierarchy of subproperties corresponding to the different kinds of extension, e.g. `conservativelyExtends`?  Maybe we should also provide a semantically equivalent alternative that is more intuitive wrt. the syntax?

**Comment by clange** [comment]
I'll move some ontology-related questions out of the ontology into issues. Can we introduce the label "ontology" for these issues?

**Comment by tillmo** [comment]
These relations are indeed relations between two OMS. In the syntax, they are attached only to one OMS, but the intended semantics is always that the relation is understood between the so-called local environment (see semantics chapter) and the OMS. The local environment is the OMS consisting of all previously-declared symbols, i.e. in an extension the OMS being extended. Maybe we should clarify this in the syntax section.

Modeling this relation as an object property indeed makes sense. (Alternatively, one could reify this into a class, but probably this is not so useful here.)

**Comment by clange** [comment]
Thanks for explaining. I will focus on the ontology for now; unless you do this clarification in the syntax section now, consider opening a new issue for it.

Re. reification: in the last round of aligning the DOL Ontology and the terminology section from the standard, we have already introduced classes that reify all of these properties. I will now make these reification connections explicit using the "reifies" annotation property (which we've had before but not yet used on these newly introduced classes).

**Comment by clange** [comment]
done, including cleaning up some problems that had resulted from the LoLa/terminology merger.
