### ISSUE TITLE
Better name for property modelBijectivelyMappableTo?

### ISSUE THREAD

**Issue by clange** [tillmo/DOL#208]
Do we have a better idea for naming the DOL Ontology property `modelBijectivelyMappableTo`? Maybe `mappableToWithBijectiveModels`?

**Comment by tillmo** [comment]
Hmm, it is not the models that are bijective, but the model part of the mapping is bijective. Maybe `mappableToBijectivelyOnModels` ?

**Comment by clange** [comment]
did this in https://github.com/clange/dol-ontology/commit/acfc21e3e8d3b20135d75a1db9aaab089b84ca08
