### ISSUE TITLE
Discuss correct SubPropertyChain for supportsLogic

### ISSUE THREAD

**Issue by clange** [tillmo/DOL#209]
In the DOL Ontology, we have

```
ObjectProperty: supportsLogic
  SubPropertyChain: inverse (isSubLanguageOf) o supportsLogic
```

Our original draft (on the board, in April 2012) said `inverse (isSubLanguageOf) o exactLogicalExpressivity`, but I think we can be a bit more general than this. OK?

**Comment by tillmo** [comment]
Agreed.
