### ISSUE TITLE
revise normative references (chapter 3)

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#21]
* provide more of them (see RFP)
* introduce a separate reference scheme

**Comment by tillmo** [comment]
look at 6.3 and 6.4. Integrate those items that are acutally reference in the DOL standard.

**Comment by fabianneuhaus** [comment]
the rfp is at
http://www.omg.org/cgi-bin/doc?ad/13-12-02.pdf

**Comment by MariaHedblom** [comment]
I added some normative references, but to be honest, I feel a bit underqualified. If anyone have time to have a look at it, please do so.
