### ISSUE TITLE
Do we need subproperties for compositions of specific types of OMS mappings?

### ISSUE THREAD

**Issue by clange** [tillmo/DOL#210]
The DOL Ontology so far has one generic property `compositionOf` for compositions of `OMSMapping`s. We would be able to enforce stronger constraints if we introduced subproperties for compositions of specific types of mappings, say, "compositions of simple theoroidal mappings". However it would be a lot of work to introduce them, and cause some redundancy.

**Comment by tillmo** [comment]
Most types of mappings are closed under composition. E.g. a composition of simple theoroidal mappings is simple theoroidal again. Hence, we do not need extra properties here, but just can write subproperty chain axioms.
