### ISSUE TITLE
changebar does not work properly

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#213]
Marking text in red with \cbs ... \cbe works well.
Simultaneously, a changebar should be added. In the first few chapters, it seems to work quite well. But later on, the changebar is missing at most places where text is marked in red. Maybe we should switch off changebars entirely and just rely on the red text?

**Comment by fabianneuhaus** [comment]
Manually making changes is not optimal. In particular, since we don't have a way of displaying the vanished text and marking up deletions. I am afraid that we will need to solve that in the finalisation  stage, where every minute change needs to be tracked.

**Comment by tillmo** [comment]
I think you misunderstood me. My suggestion is to change the definition of \cbs...\cbe in such a way that there are no changebars, but just the text is marked in red.

**Comment by fabianneuhaus** [comment]
Since we are going to automatically generate the change bars in the future, this issue is obsolete
