### ISSUE TITLE
How to specify ways of giving IRIs or URIs to all structural elements of an OMS?

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#215]
"The serialization shall specify ways of giving IRIs or URIs to all structural elements of an OMS." P. Rivett asks: how?

**Comment by clange** [comment]
In short (not at work right now): we inject such identifiers into OMS. The prerequisite for this is the main part of what we call conformance of a serialization

**Comment by tillmo** [comment]
probably we need to refer, from the sentence quoted above, to some text where this is explained in detail.

**Comment by clange** [comment]
I was wrong; the text meant something else, but my next commit will fix it.
