### ISSUE TITLE
Examples for XPointer needed

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#218]
We write:
"Standard mechanisms like XPointer (\nisref{W3C/TR REC-xptr-framework:2003}) or \nisref{IETF/RFC 5147} shall be used as means of non-destructively assigning a URI to pieces of XML or text in the given OMS serialization."
Pete Rivett asks for a couple of examples.

**Comment by clange** [comment]
I am not sure of the red formatting, hope that's OK. In any case feel free to reformat my text as you like.

**Comment by clange** [comment]
Ah, no, the red formatting highlights invalid parts of the text. Anyway, I would format this example differently from the rest of the "Standoff markup conformance" list item, as the example is non-normative. I have no idea how, because we discourage footnotes.

**Comment by tillmo** [comment]
Actually, the red formatting highlights the changed (w.r.t. the 18 May version) part of the text.
