### ISSUE TITLE
DOL ontology is inconsistent because of issues around DOLStructuredOMS

### ISSUE THREAD

**Issue by clange** [tillmo/DOL#222]
The ontology at https://github.com/tillmo/meta (I loaded dol-ontology.omn into Protégé) is inconsistent. Running the reasoner (HermiT) in Protégé 5.0 reveals that OMSReduction is unsatisfiable. The explanation for this is as follows:

    OMSReduction SubClassOf DOLStructuredOMS
      DOLStructuredOMS SubClassOf StructuredOMS
        StructuredOMS SubClassOf OMS

    OMSReduction SubClassOf OMSMapping

    DisjointClasses: OMS, OMSMapping, …

The disjointness is probably OK, because an OMSMapping is something that maps from an OMS to an OMS (see declaration of OMSMapping), so I think one of the two SubClassOf axioms is wrong.

**Comment by tillmo** [comment]
have corrected this already in August
