### ISSUE TITLE
let semantics work on MOF abstract syntax, not on EBNF abstract syntax

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#223]
Since the MOF abstract syntax is the normative abstract syntax, the (also normative) semantics should be based on it. By contrast, the EBNF abstract syntax is only informative. Note that the MOF abstract syntax does not have any constructors (like the EBNF does have), but the association ends can be used as selectors. For example, the EBNF-based semantics contains a rule for the semantics of `OMS` covering the case `reduction OMS Reduction`. In a MOF-based semantics, this would become a rule for the semantics of `ReductionOMS` (which is a subclass of `OMS`). For a `ReductionOMS` `o`, the `OMS` component can be extracted with the association end `oms`, and the `Reduction` component with `reduction` (see p. 56 of the current standard document). The association ends `oms` and `reduction` hence act like selectors.

**Comment by mcodescu** [comment]
Finished with dcea32ddec91a076c39eadbb1baf84a5b92d1b58.
