### ISSUE TITLE
Filtering of signature with language without signatures

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#224]
Assume we have an CL ontology foo and we want to reject all axioms that contain the symbol bar. How do we write that? 

ontology new = foo reject bar 

does not work because the syntax requires the second argument to be a basic OMS and "bar" is not a basic oms. It seems to me that we need to change the grammar to allow not only basic OMS but signatures as argument.

**Comment by tillmo** [comment]
Indeed, we should also allow symbol lists there. Have fixed that, see [ead7e67]
