### ISSUE TITLE
implement Conrad's comments on UML compositions

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#228]

**Comment by tillmo** [comment]
one thing remains:
define a composition declaration as an association declaration that has a composite property
Then, the notion "composition declaration" would no longer be primitive. It would be a derived notion.

**Comment by AlexanderKnapp** [comment]
I've removed "composition declarations" from the signature and the semantics.  However, it remains to change the translation into Common Logic.

**Comment by AlexanderKnapp** [comment]
Changed definition of ownerships.  Some reformatting - more usage of lstinline and lstlisting.
