### ISSUE TITLE
add construct for safety of modules?

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#23]
see end of 4.5

**Comment by yibanez** [comment]
The notion of safety would only make sense for extensions, and not for module extraction. 
That means in terms of  the DOL syntax in section 10.2.2, than we could  add '%safe' as a new production for ConsStrength. 

 Then OMS1 'and'  %safe OMS2, will have the intended meaning, OMS1 \cup OMS2 is inseparable w.r.t sign(OMS1) \cap sign(OMS2) from the empty theory. 

And something similar for OMS 'then' %safe [ExtensionName ],  ExtendingOMS

**Comment by yibanez** [comment]
After a closer look to the syntax and semantics, I realized that what I proposed above is equivalent to 
 OMS1 'and' %cons OMS2

 and OMS 'then' %con [ExtensionName ], ExtendingOMS

So, I don't think we need to add any constructor. And I will close this issue.
