### ISSUE TITLE
adapt sections about registry

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#232]
such that they are conformant with the discussion at the OMG meeting

**Comment by tillmo** [comment]
I am not sure what the outcome was. Should the mentioning of the registry be remoced entirely? We should also clarify that the registry as "basis for normative activities" means that logics, languages and translations that have been entered into the registry can later be fed into OMG standardization activities (e.g., extensions of the DOL standard).

**Comment by fabianneuhaus** [comment]
For historical reasons the registry section is in the ontology section. 
We may want to move this somewhere else. 
In particular, if we want the existence of the registry to be normative. (even if the content is informative)
