### ISSUE TITLE
Use LaTeX style used by other OMG or ISO standards

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#235]
Andrew Watson has promised to send sources

**Comment by fabianneuhaus** [comment]
Manfred promised it. I did not get a response to my emails. But I found the following
http://texdoc.net/texmf-dist/doc/latex/iso/isoman.pdf

**Comment by tillmo** [comment]
please have a look at the commit where the ISO style file has been removed: https://github.com/tillmo/DOL/commit/d00efe7ddc8351e16a88b84ec746ecc026480e12. Please try to partially undo this commit. You could even use `patch` to do this, e.g. as follows:
```
git diff d00efe7 faf627e > diff.txt
gedit diff.txt   # in editor, remove all changes that are not relevant to the switch to ISO
patch < diff.txt
```
