### ISSUE TITLE
for maintenance purposes the diagrams/figures should be numbered

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#239]

**Comment by SillyCodeValley** [comment]
I have wrapped all includegraphics in a figure environment except for one. The only thing that is left to do is giving the figures caption. I am adding here the labels for the figures to ease the search: fig:queries, fig:native_document, fig:basic_oms, fig:libraries, fig:networks, fig:oms, fig:extension&closure, fig:translations&reduction, fig:interpretations&refinements, fig:entailment&equivalence, fig:alignment, fig:modules, fig:prefixes, fig:dol-onto-classes, fig:linguistic-entity, fig:mathematical-entity, fig:semantic-entity, fig:web-entity, fig:process, fig:tool, fig:dol-onto-properties 

Or you can search for the caption-less figures be searching for the phrase: Add the caption

**Comment by tillmo** [comment]
good!
