### ISSUE TITLE
sources of ontology in annex A

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#245]
A.1 states that “The sources of the DOL ontology are being maintained in OWL Manchester syntax [27] at https://ontohub.org/meta/dol-ontology.omn.” however since the ontology is a normative part of this OMG specification it must be maintained by the OMG FTF/RTF.

**Comment by fabianneuhaus** [comment]
I suggest that we do not include this sentence. The ontology will be officially available at 
http://www.omg.org/spec/DOL/dol-language.owl
Maybe we can even put the manchester version of the document there as well. (Now that it is informative).

**Comment by tillmo** [comment]
Good idea.
