### ISSUE TITLE
merge uses cases from annex M into section 7

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#248]
Suggestion: delete M.1, M.2, move M.3 to section 7. M.4, M.5?

**Comment by fabianneuhaus** [comment]
I decided to remove M4. I did not want to add all of  M3-M5 because it would push the ratio between ontology use cases and the other use cases even more unfavourably in the direction of ontologies. M4 seemed to me to me most close to existing use cases.

**Comment by tillmo** [comment]
agreed
