### ISSUE TITLE
rework state machine example

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#256]
Ed's comments:
In Figure 7.2:
a. Since the sequence diagram and protocol state machine show the interaction between the ATM and the Bank, it would be useful to show the “BankIn” and “BankOut” interfaces for this interaction, in addition to the UserIn and UserOut interfaces. Presumable one would find the “verify”, “reenterPIN” and “verified” operations on the Bank interfaces.
b. The precondition “trialsNum >=3” cannot be made on the UserIn::keepCard operation, because the “trialsNum” attribute is defined on the ATM class, not the UserIn interface. The “trialsNum >= 3” constraint is probably better seen as an invariant on the ATM class, since it is a constraint for this specific ATM class and different ATM implementations with the same interfaces could potentially allow different numbers of trials or allow it to be configurable or some such.

7.9 Use Case Model-2: Refinements Between UML Diagrams of Different Types
1. This section should be about refinements between different types of UML models, not different types of diagrams.
2. Unfortunately, the example refinement of the protocol state machine to the ATM state machine is not clear. This is because the protocol state machine is a specific of the interaction between the ATM and the Bank, while the ATM state machine only gives the behavior of the ATM, which is just one side of this interaction. While the ATM state machine can be reduced to an abstract state machine with the two states “Idle” and “Verified” in the way shown, it is not clear how the protocol state machine can be semantically refined to the resulting reduced ATM state machine in a sensible way, because the events on the transition between the states in the protocol state machine only partially match the events in the transitions between the states in the reduced ATM state machine. In particular, if one hides “card” and “PIN”, then there is no way to transition from Idle to Verifying in the reduced ATM state machine. This is because the ATM does not react to the “verify” event, but, rather, sends a “verify” message to the Bank and it is the Bank that reacts to this event. Thus, rather than saying that the ATM behavior state machine refines the protocol state machine. It would be better to say that it is the behavior of both the ATM and the Bank that together provide a refinement of the protocol state machine. This concept of the need for the joint behavior of both parties in an interaction protocol to conform to the behavior specified by the protocol is very important, and the ability to capture this is, I think, a strong example of the value of DOL. So I would suggest that it is worth re-working this example in some detail to make it clearer and more correct.

**Comment by AlexanderKnapp** [comment]
I've changed the figure for the interfaces and the component according to Ed's comments.  For the second issue, the refinement relation, we could refer to the FASE'15 paper by Till et al., but still the notion of observation used by protocol state machines would have to be clarified.

**Comment by tillmo** [comment]
Thanks!
Concerning the second issue, we have discussed with Ed to specify a refinement from the protocol state machine into the combination of the composite structure diagram and the ATM and the bank state machine. The latter could be a network of UML models (or a union) in DOL. What do you think?

**Comment by AlexanderKnapp** [comment]
If this is possible this would be excellent. Can the "amalgamation" of the
state machines be represented in the union?
Am 02.11.2015 17:46 schrieb "Till Mossakowski" <notifications@github.com>:

**Comment by tillmo** [comment]
I think so, provided that we use the new institution devloped by @MGlauer in his master's thesis. In this institution, sentences are requirements that certain transitions are present (but a model may have more transitions than required). Then, a union is simply the union of these requirements.
