### ISSUE TITLE
correct DOL metamodel

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#257]
Ed comments:
1. The following general concerns with the metamodel have been noted previously:
a. Primitive types like String and Double should not be modeled as metaclasses but, instead, as UML primitive types String and Real should be used.
b. Primitive types and enumerations should not be targets of associations but should only be used as the types of attributes.
c. It would be better if there were a clear composition hierarchy in the metamodel. The guideline is that composition should be used if the composite part should be deleted if its “owner” is deleted. Otherwise a non-composite reference should be used.
2. Rather than being divided into multiple XMI files, the DOL metamodel should be serialized in a single XMI file, but be structured into a reasonable set of packages (one level should be sufficient). The diagrams could then be aligned with those packages. XMI 2.5 (the latest version) should also be used instead of XMI 2.1.

**Comment by tillmo** [comment]
can't this be closed now?

**Comment by MGlauer** [comment]
I am still looking through 1.c)
