### ISSUE TITLE
metamodel: OMS

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#260]
Ed:
9.4.1 Abstract Syntax
1. Page 42, diagram: QualifiedOMS::qualification is shown as having multiplicity 0..*. Shouldn’t there always be at least one qualification (multiplicity 1..*)?
2. Page 43, second bullet under “Using ExtendingOMS, further OMS can be built”: “a closure of an OMS with a Closure” Neither the diagram on this page or the concrete syntax later shows a Closure as being related to an ExtendingOMS.

Page 50, diagram:
a. The metaclass GeneralizedTerm seems unnecessary. SingleCorrespondence could just have a generalizedTerm association directly to IRI. (I don’t think GeneralizedTerm is used anywhere else.)
b. I could not find any further definition of the AlignmentCardinalityBackword and AlignmentCardinalityForward classes. Based on the concrete syntax, these are seemingly both just supposed to be AlignmentCardinalities. Perhaps AlignmentCardinality should be an enumeration in the abstract syntax metamodel, with AlignmentCardinalityPair::alignmentCardinalityBackward and alignmentCardinalityForward being attribute with this enumeration as their type.

**Comment by MGlauer** [comment]
Regarding P50 b) This modification implies that an additional constraint is necessary that ensures that an ACBackward is only present iff there is an ACForward.

**Comment by tillmo** [comment]
I have eliminated ACBackward and ACForward, see [254a164af95fc1579d9128613ff99e0c3653748a]
