### ISSUE TITLE
add constraints to metamodel

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#262]
Ed:
Page 46, third paragraph of subclause: Would it be possible to formalize the constraints in this paragraph in the abstract syntax metamodel? These constraints are important, because it is noted that the semantics in Clause 10 assume they hold.

**Comment by MGlauer** [comment]
@tillmo Should "Mapping a non-logical symbol twice is an error" be added as an OCL constraint?

**Comment by tillmo** [comment]
Yes please. Since there is a faithful functor from the signature category into Set, each signature morphism has an underlying symbol function.

**Comment by MGlauer** [comment]
@tillmo: I added the constraint that Symbol Map is a (partial) mapping. Could you remove the remark "A symbol map in an interpretation is \required to cover all
non-logical symbols of the source OMS; the semantics specification in
\cref{c:semantics} makes this assumption."?

**Comment by tillmo** [comment]
When thinking about it, I have to revise my statement: since we have the symbol functor, it should indeed be a total function. So the remark should stay.

**Comment by MGlauer** [comment]
This raises the initial problem again: non-logical symbols are not an accessible part of an OMS in the abstract syntax

**Comment by tillmo** [comment]
True. But in the DOL semantics, we can compute the set of symbols of an OMS, and hence check this condition. Hence, the mentioned remark should stay, although it cannot be checked using OCL constraints.
