### ISSUE TITLE
issues about CURIEs

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#263]
Ed writes:
9.6.2 Abbreviating IRIs using CURIEs
1. Page 53, last paragraph, second sentence: “Informatively, the CURIE grammar supported by DOL can be restated as follows:” The CURIE grammar given informatively in 9.6.2 is repeated again (identically) in 9.6.4, where it is presumably normative. It needs to be clarified whether this grammar is normative or informative. In any case, it should only be given in one place (probably 9.6.4).
9.6.4 Concrete Syntax
1. Page 55, CURIE: The production ends in “-“. Is there something missing here, or is this a typo? If the latter, what is the difference between a CURIE and a MaybeEmptyCURIE?

**Comment by clange** [comment]
Re 9.6.2: fixed
Re production ending in "-": "A -" means "A but not the empty word" (see #85 for discussion)
