### ISSUE TITLE
strengthen “Standoff markup conformance”

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#264]
Ed:
Page 57, list item “Standoff markup conformance”: This sentence is stated as a normative requirement (using “shall”), but the requirements is for “standard mechanisms like” a couple of examples given. This is weak for a normative requirement, since it actually leaves largely open to interpretation what a “standard mechanism” is. Can this requirement be more strongly worded, at least giving XML contexts, say, in which XPointer or IETF/RFC 5147 must be used?

**Comment by clange** [comment]
While working on this I realised that there is also a gap in the definition of XML conformance. I am currently fixing both.
