### ISSUE TITLE
in section 9, add cross-references to section L

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#266]
each syntactic constructs should be accompanied with cross-references to examples in section L (or in section 7)

**Comment by tillmo** [comment]
@okutz, since this issue has not been assigned to anyone yet and you only have some smaller issues so far, I have assigned it to you.

**Comment by okutz** [comment]
new file: Linking_Annex-L_to_DOL-keywords.txt
records the examples of Annex L with labels and the introduction of relevant keywords

**Comment by tillmo** [comment]
Thanks, @okutz. Can this issue be closed now?
