### ISSUE TITLE
define some notion of “interoperability” that is tailored to this OMG Specification

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#27]
see 4.10

**Comment by tillmo** [comment]
from the old issue: phrase "logical interoperability" more precisely, based on the previously introduced terms - also see: ability of two or more systems to exchange information and to mutually use the information that has been exchanged. Defined in: ISO/IEC TR 10000-3:1998, 3.2.7

**Comment by gruninger** [comment]
Incorporated additional text into definition
