### ISSUE TITLE
correct latex-diff output

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#272]
with
```
latexdiff-git -r 2e94c79 --force --exclude-textcmd="section,subsection" OMG_OntoIOp_current.tex 
```
we get some useful diff showing the difference w.r.t. to the August 24 version.
However, a textual diff
```
git diff 2e94c79
```
shows e.g.
```
+\termdefinition{infrastructure axiom}{axiom that is used in the
+target of a logic translation in order to encode a signature
+of the source logic}
+\begin{example}
+ The translation from OWL to multi-sorted first-order logic translates
+ each OWL built-in type to its first-order axiomatization as a
+ datatype. These first order axioms are infrastructure axioms.
+\end{example}
```
and this paragraph is only partially marked blue in the latex diff.

Maybe this is related to the lots of errors that latex-diff outputs.

**Comment by tillmo** [comment]
deadline: Mon, Nov 2

**Comment by tillmo** [comment]
I suggest to try the latest version of latex-diff (I tried the one shipped with Ubuntu Trusty, which is probably not the newest one).

**Comment by SillyCodeValley** [comment]
When writing a latexdiff-git command, you need to add one more argument:

latexdiff-git -r 2e94c79 --force --exclude-textcmd="section,subsection" --append-textcmd="termdefinition"  OMG_OntoIOp_current.tex

This will solve the problem given above. 

I am still working on the highlight problems related to lstlisting and math environment.

**Comment by tillmo** [comment]
could you please let the input and the output file be parameters of the python script? Then we can more easily adapt to a new base git revision in the (near) future.

**Comment by SillyCodeValley** [comment]
Hello Till,

Sorry I saw your message late....
I have made the changes....

Bests
Madhura

**Comment by tillmo** [comment]
please check in the new script
