### ISSUE TITLE
correct AlignmentCard in metamodel

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#275]
in the EBNF abstract syntax and the concrete syntax, I have simplified the rules involving AlignmentCard. This should also be reflected in the MOF metamodel.

**Comment by MGlauer** [comment]
@tillmo: This change does not map to UML, as there are multiple Classes in a single option. We need the following EBNF with an additional constraint ensuring that a there are exactly two or none AlignmentCards:

AlignmentDefinition ::= alignment-definition AlignmentName
                              [AlignmentCardinality] [AlignmentCardinality]
                              AlignmentType Correspondence*
                              [AlignmentSemantics]

**Comment by tillmo** [comment]
OK, can you directly change the EBNF?
