### ISSUE TITLE
Why view and interpretation as different classes

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#277]
Can't we delete one of them and use "alternative label" to introduce the second label?

**Comment by tillmo** [comment]
this is a matter of taste. @clange, what do you think?

**Comment by clange** [comment]
Why not. In the terminology section, the first term is "interpretation", so I'd suggest to keep the ontology class Interpretation, and add "view" as a skos:altLabel. OK?

**Comment by fabianneuhaus** [comment]
I would prefer that. Less clutter. :-)

**Comment by tillmo** [comment]
@clange, could you please implement that?

**Comment by clange** [comment]
Done, but note: `View` had a `skos:note` that `Interpretation` didn't have and that didn't exist in the standard. I have, for now, deleted this note. OK?

        skos:note "When an interpretation is given as a set of correspondences, these are given as tuples, where the type of relationship is given by the specific kind of interpretation."@en

**Comment by tillmo** [comment]
OK
