### ISSUE TITLE
Cite all normative references with date or version number (also using versioned specification URL)

### ISSUE THREAD

**Issue by clange** [tillmo/DOL#288]
For some normative references (e.g. NR23) no date or version is cited, so it's not clear which version we are using. For others (e.g. NR25 or NR28) the plain text refers to a date, but the URL is the unversioned one.

Instead, dates _and_ versioned URLs should be used always (see e.g. NR18 or NR22).

**Comment by tillmo** [comment]
@clange, wouldn't it be easier to just cite the versionless reference and URL? This will always refer to the lastest released version. (I think some OMG person has even suggested this.) Only in cases where we definitely rely on a specific version, we should cite that one.

**Comment by clange** [comment]
Whatever the OMG suggests is fine with me.

**Comment by clange** [comment]
Hm, there are at least a few such references that do depend on a specific version. E.g. wherever we cite RDFa for CURIEs we refer to section 6. In later versions of RDFa CURIEs will probably still be specified as we need them, but not necessarily in section 6.

BTW you might ask me to check such things everywhere, but today I'm mostly of the computer and won't have the capacity to do this :-(

**Comment by clange** [comment]
In the branch https://github.com/tillmo/DOL/tree/288_references, I changed several references from "versioned" to "unversioned".

I did leave the dates of publication in place, as some of your existing unversioned references also had dates. Note BTW that the W3C makes major versions a part of the name of a standard, e.g., OWL 2 needs to be referred to as "OWL 2", not as "the current version of 'OWL'".

I left the following normative references versioned because we are referring to a specific section of the standard document: RDF, RDFa, XMLns, OWL2RDF.

**Comment by tillmo** [comment]
see 288_references
Text for FTF: we have changed several references from "versioned" to "unversioned".
We left the following normative references versioned because we are referring to a specific section of the standard document: RDF, RDFa, XMLns, OWL2RDF.

**Comment by tillmo** [comment]
note that I have rebased the branch on master instead of develop. This means that if you have had a local copy already, you will get a conflict, and need to do a
```
git fetch
git co 288_references
git reset --hard origin/288_references
```

**Comment by fabianneuhaus** [comment]
issue http://issues.omg.org/browse/DOL-96
