### ISSUE TITLE
syntax of refinements

### ISSUE THREAD

**Issue by mcodescu** [tillmo/DOL#289]
With the latest changes in the syntax, a refinement can be written: `Refinement refined via Refinement to Refinement`. Is this intended?

**Comment by mcodescu** [comment]
even
`Refinement refined via Refinement, Refinement,...Refinement to Refinement`
is allowed

**Comment by tillmo** [comment]
yes. Note that the first and the last refinements must be refinements of networks, while the middle refinements must be refinements of OMS.
