### ISSUE TITLE
Constraints in abstract syntax

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#294]
part of issue #261 
Ed wrote: 

2. Page 45, ConservitivityStrength, ExtConservitivityStrength, Conservative: These concrete syntax productions make it clear that there are certain conservativity strengths that can only be used in certain contexts. It would be best if these restrictions were also recorded as constraints in the abstract syntax metamodel.

Has this been resolved?

**Comment by MGlauer** [comment]
@tillmo I remember you merged ConservitivityStrength, ExtConservitivityStrength, Conservative in the abstract syntax during the migration from EBNF to MOF. Shall I remodel the distinction between those using OCL?

**Comment by tillmo** [comment]
yes, good idea.
