### ISSUE TITLE
Conformance Language, Logic, and serialization 

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#295]
It currently says:
*************************
For any conforming OMS language, logic, and serialization of an OMS language, it is required that it be assigned an HTTP IRI, by which it can be identified. It is also required that a machine-processable description of this language/- logic/serialization is retrievable by dereferencing this IRI; this requirement follows the linked data principles W3C/TR REC-ldp-20150226:2015. As a minimal requirement, there must be a RDF description conforming to the vocabulary specified in annex B. That description must be made available in the RDF/XML serialization when a client requests content of the MIME type application/rdf+xml. Descriptions of the language/logic/serialization in further representations, having different content types, may be provided.
*************************

I have several questions:
- shouldn't the registry mentioned here? Shouldn't we being registered in the DOL registry make mandatory for DOL conformance
-  "As a minimal requirement, there must be a RDF description conforming to the vocabulary specified in annex B." -- There are two problems: since the ontology is now informative, I don't believe it can be used in the conformance section. Further, there are no requirements about the content. (Would an empty RDF file count?)

**Comment by tillmo** [comment]
I think we should move the whole paragraph to the registry section in annex A (and modify it in order to integrate it there).
