### ISSUE TITLE
I.5.7 OWL->FOL

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#301]
I.5.7.2 Translation of sentences: $\top$ and $\bot$ are missing!
I.5.7.3 Translation of models: 
* $M'_\Thing$ does not make sense, because this is unsorted first-order logic. 
* $\I$ has not been introduced. Sometimes, $I$ is used. 
* Typo: By Induction (should be: by induction).
* As last item, add: The other cases are similar.
* The satisfaction condition holds as well. --> The satisfaction condition now follows easily.

**Comment by tillmo** [comment]
see 301_translation_OWL_to_FOL
Text for FTF: we have made minor technical corrections in the mathematical definition of the translation of OWL to first-order logic.

**Comment by fabianneuhaus** [comment]
OMG ticket added
http://issues.omg.org/browse/DOL-81

**Comment by fabianneuhaus** [comment]
OMG proposal added
