### ISSUE TITLE
model --> realisation

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#302]
in the semantics chapter, replace ``model'' (in an institution) by ``realisation'', in order to avoid confusion with ``model'' in the sense of ``MDE model''?

**Comment by tillmo** [comment]
see 302_realisation_for_model
Text for FTF: we have changed the term "model" into "realisation" and the term "MDE model" into "model", because in the OMG community, the term "model" will be unterstood in the sense of MDE and not in the sense of logical model theory. This makes certain sentences much clearer, e.g. on p. 119, "models (in the sense of the term defined in clause 4) of UML class models" now becomes "realisations of UML class models".

**Comment by fabianneuhaus** [comment]
I hope you spelled realization with a "z" ...

**Comment by fabianneuhaus** [comment]
Could you globally replace "realisation" by "realization" (we are using American English in the rest of the document) and then regenerate the diff?

**Comment by tillmo** [comment]
done

**Comment by fabianneuhaus** [comment]
omg proposal added

**Comment by fabianneuhaus** [comment]
OMG proposal added

**Comment by fabianneuhaus** [comment]
http://issues.omg.org/browse/DOL-82
