### ISSUE TITLE
The name of the OMS language graph class in the ontology does not match its label

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#304]
The class, dol:LanguageGraph has a label of "OMS language graph", which is more explicit. If that is the intent of the class from a usage perspective, the name should be revised to dol:OMSLanguageGraph.

(API4KB team input)

see http://issues.omg.org/browse/DOL-1

**Comment by tillmo** [comment]
see 304_OMS_language_graph in the DOL ontology repo.
Text for TFT: we have implemented the suggested change.

**Comment by fabianneuhaus** [comment]
I don't see a file 304.diff

**Comment by tillmo** [comment]
right, added it.

**Comment by tillmo** [comment]
right, added it.

**Comment by fabianneuhaus** [comment]
OMG proposal added
