### ISSUE TITLE
The definition of dol:AbstractSyntax implies that it should be a subclass of dol:Language

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#305]
The definition of dol:AbstractSyntax says it is a (term) language that ... . Therefore It should be a subclass of dol:Language.

Also, the definition dol:AbstractSyntax does not capture the common notion of abstract syntax in OMG. Perhaps "platform-independent metamodel for a language"?

(API4KB team)

see http://issues.omg.org/browse/DOL-2

**Comment by tillmo** [comment]
see 305_abstract_syntax of the DOL ontology repo.
Text for FTF: AbstractSyntax is now a subclass of Language. The notion of metamodel occurs in a note; we have kept the definition more general.

**Comment by fabianneuhaus** [comment]
OMG proposal added
