### ISSUE TITLE
Elements described as "logical theories" are not defined as such

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#307]
Each of "dol:Ontology", "dol:Specification" and "dol:MDEModel" are defined as "logical theories", but they are not subclasses of dol:LogicalTheory. Further, their definition suggests they are roles (i.e. non-rigid properties) of dol:LogicalTheory. If this is the intended meaning, then the definition should say this explicitly.

(API4KB team)

http://issues.omg.org/browse/DOL-4

**Comment by tillmo** [comment]
Indeed, the use of "logical theory" for the definitions is misleading here. New Proposal for notes:
 * OMS: An OMS is a collection of expressions (like non-logical symbols, sentences and structuring elements) in a given OMS language (or several such languages) and denoting a class of models and, possibly, a logical theory
 * ontology: explicit and shared formal representation of a conceptualisation of a domain or of fundamental notions, including a controlled vocabulary and a taxonomy
 * MDE model: explicit and formal representation of (the development of) a system, e.g. a hardware, software or information system or an organisation
 * specification: property-oriented formal representation of requirements or specific designs of a system

**Comment by fabianneuhaus** [comment]
I don't see a diff file in the ontology repo.

**Comment by tillmo** [comment]
right, I added it.

**Comment by fabianneuhaus** [comment]
The definition  of OMS in the spec
"OMS (ontology, specification or MDE model) basic OMS or structured OMSa basic or structured ontology, specification or MDE model."
das not match the text above.

**Comment by tillmo** [comment]
OK, changed it.

**Comment by fabianneuhaus** [comment]
I thought more about the definition of ontology. I still don't like the one above. What do you think about the following (based on a definition by Barry Smith, who also tries to avoid "conceptualization"):  
Ontology Definition: explicit and shared formal representation of the entities and their interrelationships of a given domain of discourse 
Note: The explicit and shared formal representation is materialised in some OMS language  (or several such languages). 
Note: Ontologies also include definitions and explanations in natural language that capture the intended meaning of the formal expressions.  
Note: Ontologies typically include a taxonomy and, frequently, a partonomy.

**Comment by tillmo** [comment]
OK, changed it in both the document and the ontology, but used "explicit and shared formal representation of the entities and their interrelationships of a given domain of discourse or of fundamental notions" as definition.

**Comment by fabianneuhaus** [comment]
OMG proposal added
