### ISSUE TITLE
Potential misclassification of several classes

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#308]
The definition of dol:OMS suggests it should be a disjoint union of dol:Ontology, dol:Specification and dol:MDEModel, while formally they are subclasses. It is not clear if dol:OMS should be considered a role, or a subclass of logical theory. Based on the note attached to OMS, which says "an OMS is a collection of expressions, like ...", I would expect that OMS is a subclass of logical theory, not a role. Therefore, dol:Ontology, dol:Specification and dol:MDEModel would not be subclasses of OMS, but roles that an OMS can play.

(API4KB team)

see http://issues.omg.org/browse/DOL-5

**Comment by tillmo** [comment]
already covered by #307 and http://issues.omg.org/browse/DOL-4 , resp.

**Comment by fabianneuhaus** [comment]
OMG proposal added
