### ISSUE TITLE
Need for intermediate class to disambiguate OWL 2 profiles

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#309]
There appears to not be an intermediate concept between dol:OMSLanguage and dol:Profile for a dol:OMSLanguage with a particular logic (e.g. OWL2 with Direct Semantics).
While this is not an error of the DOL ontology, this is a concept that would be useful for API4KB.

We are surprised that this concept is not needed in DOL, because e.g. this concept enables the distinction between OWL 2 (in general) and OWL DL or OWL Full, It would also potentially be needed to distinguish between OWL 2 profiles.

(API4KB team)

see http://issues.omg.org/browse/DOL-6

**Comment by tillmo** [comment]
The philosophy of DOL is different here: an OMSLanguage can support (via the object property supportsLogic) different Logics. What you are after is a pair of an OMSLanguage and a Logic (such that the supportsLogic relation holds). We do not have such a thing in DOL as a concept of its own, although implicitly it is there: a user can select an OMSLanguage and a Logic, for example OWL2 EL with RDF logic (i.e. RDF semantics, aka OWL full).

**Comment by fabianneuhaus** [comment]
OMG proposal added
