### ISSUE TITLE
Missing concept for Symbol in the DOL ontology

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#310]
There is no concept of Symbol but it is used in the definition of Language, and there is a concept of NonLogicalSymbol.

(API4KB team)

see http://issues.omg.org/browse/DOL-7

**Comment by tillmo** [comment]
see 310_symbol in the DOL ontology repo.
Text for FTF: We have added classes Symbol and LogicalSymbol.

**Comment by fabianneuhaus** [comment]
omg ticket added
