### ISSUE TITLE
The text definition of dol:Mapping does not agree with the way the class is specified.

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#311]
The natural language definition of dol:Mapping does not agree with the formalization, in that logic mappings are not set-theoretic mappings, but are families of set-theoretic mappings. The natural language definition could be generalized to "set-theoretic mapping or family of set-theoretic mappings" (as suggested by Till), so that it would be correct to say that dol:LogicMapping is a subclass of dol:Mapping. This would still exclude dol:SignatureMorphism.

see http://issues.omg.org/browse/DOL-8

**Comment by tillmo** [comment]
see 311_mapping in the DOL ontology repo.
Text for FTF: we have generalized the definition to "set-theoretic mapping or family of set-theoretic mappings".

**Comment by fabianneuhaus** [comment]
OMG proposal added
