### ISSUE TITLE
Need to clarify what is meant by a "construct" in the ontology

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#312]
The term "construct" is used in several annotations (:isLanguageAspectOf definition, :LanguageAspect, ...). Is this a synonym for dol:Term or dol:Expression or something different? To make this more clear, either a term dol:Construct could be defined, or an existing concept could be used instead.

(API4KB team)

see http://issues.omg.org/browse/DOL-9

**Comment by tillmo** [comment]
see 312_construct in the DOL ontology repo.
Text for FTF: We have now defined construct as "syntactic pattern that is part of a language".

**Comment by fabianneuhaus** [comment]
OMG proposal added
