### ISSUE TITLE
Need to clarify the role of logical symbols in the ontology

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#313]
The natural language definition of Term "syntactic expression either consisting of a single non-logical symbol or recursively composed of other terms (a.k.a. its subterms)" is a little unclear, as it leaves some question as to the role of logical symbols. The intent is made more clear by the existence of the subclass Sentence, which presumably includes sentences with logical connectives, but as a stand-alone definition it is vague. Perhaps an explanatory note could be added, because in some standards the "term" class does not include sentences.

see http://issues.omg.org/browse/DOL-10

**Comment by tillmo** [comment]
see 313_term_logical_symbol of the DOL ontology repo.
Note for FTF: we have clarified that logical symbols can be part of terms.

**Comment by fabianneuhaus** [comment]
diff is missing
the change seems not to address the question concerning sentences. Maybe there should be an additional note?

**Comment by tillmo** [comment]
added the diff. I think we do not need to mention sentences, because these mainly helped them to understand what is going on. But our solution is much clearer now, so sentences are not needed as a bridge enabling understaning.

**Comment by fabianneuhaus** [comment]
omg proposal added
