### ISSUE TITLE
Need to clarify the use of "text" in the ontology

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#314]
In dol:OMSLanguageTranslation the use of "text" in the note suggests that a translation is always between texts (presumably, a coarse-grained syntactic category like Common Logic texts?), rather than between the more fine-grained syntactic "constructs". It would be more clear to either define "dol:Text" and "dol:Construct" or re-use terms that are formally defined, such as dol:Term or dol:Expression.

(API4KB team)

see http://issues.omg.org/browse/DOL-11

**Comment by tillmo** [comment]
see 314_use_of_text of the DOL ontology repo.
Text for FTF: We have entierly avoided the use of a term specififying the nature of the result of the translation here.

**Comment by fabianneuhaus** [comment]
OMG proposal added
