### ISSUE TITLE
There are multiple definitions for dol:OMSLanguageTranslation in the ontology which should be clarified and distilled to a single definition

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#315]
dol:OMSLanguageTranslation has two definitions with slightly different wording. One says "a mapping (translation or reduction) between two OMS languages", which seems like it would be more appropriate for dol:OMSLanguageMapping, a concept that is not explicitly defined. The second says "mapping from constructs in the source OMS language to their equivalents in the target OMS language". It is not clear in what sense "equivalent" is meant here.

(API4KB team)

see http://issues.omg.org/browse/DOL-12

**Comment by tillmo** [comment]
see 315_OMSLanguageTranslation of DOL ontology repo.
Text for FTF: the first wording has been corrected already by http://issues.omg.org/browse/DOL-28 . We have deleted the second wording, because it is imprecise and mostly inherited from Mapping already.

**Comment by fabianneuhaus** [comment]
omg proposal added
