### ISSUE TITLE
Redundant declaration of dol:OMSLanguageTranslation in the ontology

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#316]
There is a redundant declaration of dol:OMSLanguageTranslation as a subclass of dol:Mapping, in addition to it being a subclass of dol:LanguageMapping, which could be deleted.

see http://issues.omg.org/browse/DOL-13

**Comment by tillmo** [comment]
has been taken care of in #331

**Comment by fabianneuhaus** [comment]
OMG proposal added
