### ISSUE TITLE
There are redundant axioms for LogicTranslation and LogicReduction

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#317]
There is a similar group of redundant axioms for subclasses of LogicTranslation and LogicReduction, that explicitly state they are subclasses of LogicMapping. It should be okay to delete these redundant declarations.

(API4KB team)

see http://issues.omg.org/browse/DOL-14

**Comment by tillmo** [comment]
see 317_axioms_for_logic_translation_and_reduction of the DOL ontology repo.
Note for FTF: we have removed the redundant axiom for Embedding, which is a subclass of LogicTranslation. There is no subclass of LogicReduction.

**Comment by fabianneuhaus** [comment]
OMG proposal added
