### ISSUE TITLE
Clarify the definition of dol:OMSLanguageTranslation

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#318]
Add a note (if it is true) that an dol:OMSLanguageTranslation could also be called an dol:OMSLanguageMapping, since the formalization simply requires that the mapping be from and to OMS Languages.

(API4KB team)

see http://issues.omg.org/browse/DOL-15

**Comment by tillmo** [comment]
Text for FTF: an OMSLanguageMapping can be an OMSLanguageTranslation or (newly added, see http://issues.omg.org/browse/DOL-28 and http://issues.omg.org/browse/DOL-16) an OMSLanguageReduction. So no change needed here.

**Comment by fabianneuhaus** [comment]
omg proposal added
