### ISSUE TITLE
Clarify the definition of dol:LogicMapping in the ontology

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#320]
The definition of Logic Mapping suggests that it can be any kind of mapping between logics, but the comment says it should be either a translation or reduction, which seems to be more specific. Should LogicMapping be the disjoint union of LogicTranslation and LogicReduction?

(API4KB team)

see http://issues.omg.org/browse/DOL-17

**Comment by tillmo** [comment]
Text for FTF: LogicTranslation and LogicReduction are not disjoint. The extreme case of a LogicMapping that leaves everything unchanged (the identity mapping) is both a  LogicTranslation and a LogicReduction.
Moreover, in the future, there could be LogicMappings that are neither LogicTranslations nor LogicReductions (although it is presently not clear how they would look).
Hence, we prefer to leave the ontology unchanged here.

**Comment by fabianneuhaus** [comment]
OMG proposal added
