### ISSUE TITLE
Revise/clarify the definition and related notes for dol:LogicReduction in the ontology

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#321]
LogicReduction has a note "mapping between logics forgetting parts of the structure, projection to a smaller logic, in contrast to reduction". Should be "mapping between logics forgetting parts of the structure, projection to a smaller logic, in contrast to translation"

(API4KB team)

see http://issues.omg.org/browse/DOL-18

**Comment by tillmo** [comment]
already covered by #331 
Text for FTF: we have changed this accordingly.

**Comment by fabianneuhaus** [comment]
OMG proposal added
