### ISSUE TITLE
Definition of dol:Language needs clarification

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#322]
The definition of dol:Language as "collection of expressions" where dol:Expression is "a finite combination of symbols that are well-formed according to applicable rules (depending on the language)" suggests that this class does not include natural languages, only formal languages. This is supported by its usage in the definition of dol:FormalSemantics? To avoid confusion, could this concept be renamed to dol:FormalLanguage (if that is the intent)?

(API4KB team)

see http://issues.omg.org/browse/DOL-19

**Comment by tillmo** [comment]
see 322_Language of the DOL ontology repo.
Text for FTF: we now distinguish class Language and class FormalLanguage.

**Comment by fabianneuhaus** [comment]
omg proposal added
