### ISSUE TITLE
IRIs in the "global environment" are overly constrained

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#324]
In the DOL ontology, IRIs seem to be restricted to document identifiers, networks and mappings, and the meaning of global knowledge remains unexplained.
see http://issues.omg.org/browse/DOL-21

**Comment by tillmo** [comment]
see 324_global_environment in both the DOL repo as well as the DOL ontology repo.
Text for DOL FTF: We have changed the wording concerning global knowledge. However, we did not change anything concerning IRIs. Note that a GlobalEnvironment uses IRIs in a specific and restricted way. But this does not mean at all that IRIs (which are not defined in the DOL ontology, because there are other places to do so) are restricted.

**Comment by fabianneuhaus** [comment]
omg proposal added

**Comment by fabianneuhaus** [comment]
todo: add diff from DOL repo
