### ISSUE TITLE
Language graphs should not be limited to translations

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#325]
In  the DOL ontology, LanguageGraph: edges seem to be limited to language translations - why not e.g. language reductions?

The definition of OMSLanguageTranslation suggests that a language mapping can be either a translation or a reduction.

see http://issues.omg.org/browse/DOL-22

**Comment by tillmo** [comment]
see 325_language_reductions of git@ontohub.org:meta.git
Text for FTF: we have added language reductions to the definition of LanguageGraph.

**Comment by fabianneuhaus** [comment]
OMG proposal added
