### ISSUE TITLE
Nodes and edges are not well defined

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#326]
In the DOL ontology, LanguageGraph and LogicGraph: Explicitly state what the nodes and what the edges are

see http://issues.omg.org/browse/DOL-23

**Comment by tillmo** [comment]
see 326_define_nodes_and_edges of git@ontohub.org:meta.git
Text for FTF: we have now explicitly stated what nodes and edges are.

**Comment by fabianneuhaus** [comment]
@tillmo I believe the diff is not correct. It is about LanguageMapping, but you changed the definition of LogicGraph

**Comment by tillmo** [comment]
The diff is not about LanguageMapping. A diff consists of a sequence of hunks. Each hunk starts with @@, and provided some context around the changed lines. Please look at the context at the start of a hunk, not at the end.

**Comment by fabianneuhaus** [comment]
Is there a way to guarantee that the hunk includes the relevant class declaration? Because the information that the second hunk is about LogicGraph is missing.

**Comment by fabianneuhaus** [comment]
OMG proposal added

**Comment by tillmo** [comment]
with `git diff -Un` one can enlarge the context of a hunk to n lines (default is 3).
