### ISSUE TITLE
Documentation is missing in the DOL ontology for the meaning of HeterogeneousEnvironment

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#327]
HeterogeneousEnvironment: the notes from the document should also be added to the ontology class.

see http://issues.omg.org/browse/DOL-24

**Comment by tillmo** [comment]
see 327_notes_on_heterogeneous_environment of git@ontohub.org:meta.git
Text for FTF: We have added the notes to the class HeterogeneousEnvironment of the DOL ontology.

**Comment by fabianneuhaus** [comment]
OMG proposal added
