### ISSUE TITLE
The text definition for Institution is incomplete

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#328]
In the DOL ontology, the natural language (text) definition for the Institution class is incomplete, and should incorporate the definition provided by the defining axioms of the class.
see http://issues.omg.org/browse/DOL-25

**Comment by tillmo** [comment]
see 328_definition_of_institution of git@ontohub.org:meta.git
Text for FTF: we have extended the definition of institution accordingly.

**Comment by fabianneuhaus** [comment]
OMG proposal added
