### ISSUE TITLE
The definition for Logic in the DOL ontology is limited to monotonic logic only and should be broader

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#329]
Logic: the definition seems to be appropriate for monotonic logic only. That is, the satisfaction relation is defined for sentences, and then it appears to be assumed that satisfaction of a theory is based on satisfaction of all sentences in the theory. This would not be enough for, e.g. defeasible logic. So perhaps the name of this concept should be changed to MonotonicLogic, so if can be reused in external ontologies that also cover nonmonotonic logics.
see http://issues.omg.org/browse/DOL-26

**Comment by tillmo** [comment]
fixed, see branch 329_non_monotonic_logics of git@ontohub.org:meta.git

**Comment by tillmo** [comment]
or of https://ontohub.org/meta

**Comment by fabianneuhaus** [comment]
I need either some text or some diff-file in order to be able to close the ticket on OMG's site.

**Comment by fabianneuhaus** [comment]
to be more precise: if text was replaced, I need the text that was removed and the text it was replaced with.

**Comment by tillmo** [comment]
I have added a diff for the ontology (it is an RDF diff, but OMG wants RDF...) and a textual description of the diff.

**Comment by fabianneuhaus** [comment]
hallo Till, 
Ich finde kein Diff-file. Wo und unter welchen Namen finde ich das Diff und die textual description? 
Viele Grüße
Fabian

**Comment by tillmo** [comment]
sorry, I forgot to push... fixed now.

**Comment by fabianneuhaus** [comment]
Added proposal to JIRA
