### ISSUE TITLE
The DOL ontology definition of logical theory needs work

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#330]
In the DOL ontology for LogicalTheory: The natural language definition is kind of awkward: "a signature together with a set of sentences" would be more appropriate.
see http://issues.omg.org/browse/DOL-27

**Comment by tillmo** [comment]
see 330_logical_theory of git@ontohub.org:meta.git
Text for DOL FTF: we have changed the wording as suggested, but kept the addition "(over that signature)".

**Comment by fabianneuhaus** [comment]
omg proposal added.
