### ISSUE TITLE
The concepts Reduction and Translation are lacking in the ontology

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#331]
In the ontology, classes for Reduction and Translation (as subclasses of Mapping) would be useful (and then define logic and language reduction and translation using them).
see http://issues.omg.org/browse/DOL-28

**Comment by tillmo** [comment]
see 331_translation_and_reduction of git@ontohub.org:meta.git
Text for DOL FTF: we have added classes Reduction, Translation and OMSLanguageReduction.

**Comment by tillmo** [comment]
see 331_translation_and_reduction of git@ontohub.org:meta.git
Text for DOL FTF: we have added classes Reduction, Translation and OMSLanguageReduction.

**Comment by fabianneuhaus** [comment]
omg ticket added

**Comment by fabianneuhaus** [comment]
I stumbled over this definition: 
>a mapping (translation) between two OMS languages that keeps or encodes the structure</skos:definition>
It seems incomplete. The structure of what?

**Comment by tillmo** [comment]
OK, perhaps better "keeps or encodes the content of the source"?

**Comment by fabianneuhaus** [comment]
Definition: Mapping from constructs in the source OMS language to constructs in the target OMS language. 
Note: Typically the mapping is selected with  the goal to preserve the intended meaning when translating from the source to the target OMS language.

**Comment by tillmo** [comment]
No, your proposal will not capture the difference between translation and reduction. I have commited a new definition, avoiding the term "structure".

**Comment by fabianneuhaus** [comment]
revised version uploaded to JIRA
