### ISSUE TITLE
There is a need for the concept of a mapping that is not a logic mapping

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#332]
Currently in the DOL ontology, DefaultMapping is defined as a subclass of LogicMapping. There might be a need for DefaultLanguageMappings, so it would be better to rename this class to DefaultLogicMapping and have a superclass named DefaultMapping (especially the fact that the document speaks of default language translations hints to the existence of a default language mapping).

see http://issues.omg.org/browse/DOL-29

**Comment by tillmo** [comment]
see 332_default_mapping of git@ontohub.org:meta.git
Text for FTF: we have changed DefaultMapping into DefaultLogicMapping, and added DefaultLanguageMapping and (as a superclass of both) DefaultMapping.

**Comment by fabianneuhaus** [comment]
OMG proposal added
