### ISSUE TITLE
Basic definitions are missing from the DOL ontology

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#335]
On page 4 of the specification document, it states that " DOL is capable of assigning identifiers to entities (symbols, axioms, modules, etc.)." Based on this, we expect to find classes for symbol, axiom and module in the ontology. Is AxiomSentence the same as "axiom"? Definitions for some of these concepts appear to be missing from the ontology, in other words.

see http://issues.omg.org/browse/DOL-32

**Comment by tillmo** [comment]
Text for FTF: We have changed AxiomSentence into Axiom (and TheoremSentence into Theorem). Symbol occurs as NonLogicalSymbol in the ontology, in accordance to section 4.2 of the DOL document. On page 4, they are (for conciseness) mentioned as "symbols". Module is a class in the ontology.

**Comment by tillmo** [comment]
see 335_basic_definitions of git@ontohub.org:meta.git

**Comment by fabianneuhaus** [comment]
added Proposal to JIRA
