### ISSUE TITLE
The definition of DOLLibrary does not match its specification in the ontology

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#336]
DOLLibrary is formalized as "semanticallyDenotes some GlobalEnvironment", but this doesn't seem to arise from the natural language definition.

see http://issues.omg.org/browse/DOL-33

**Comment by tillmo** [comment]
see branch 336_DOL_Library of git@ontohub.org:meta.git
Note that `hasPart` is maybe not entirely precise, instead, `hasOptionalPart` would be more precise. However, this will lead to more complexity. Hence, I decided to interpret `hasPart` as the possibility to have such a part here.

**Comment by tillmo** [comment]
I think it is easier to post the text here, instead of having a separate file (because it then can be easier discussed and corrected). So here it is (OK, this time copied from 336.txt):

A DOLLibrary is now (additionally) formalised as having OMS, OMSMappings and OMSNetworks as parts.

**Comment by fabianneuhaus** [comment]
added proposal to JIRA
