### ISSUE TITLE
The concept "sequence of correspondences" is defined but not used

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#337]
In the DOL ontology, dol:SequenceOfCorrespondences doesn't appear to be used for anything. Consider deleting.

(Note that any deletions must be done prior to moving into RTF – at that stage in the specification one cannot delete or rename concepts or properties - you would need to deprecate them instead, so that your user community is not negatively impacted.)

see http://issues.omg.org/browse/DOL-34

**Comment by tillmo** [comment]
I have changed alignments to consist of sequences of correspondences, see 337_sequence_of_correspondences of git@ontohub.org:meta.git
@fabianneuhaus, how do I express that a `SequenceOfCorrespondences` consists of `Correspondence`s?

**Comment by fabianneuhaus** [comment]
hasElement

**Comment by tillmo** [comment]
I just have seen that there already is `hasSequenceMember` and its converse, `isMemberOf`. However, there are no domain and range declarations, because it does not make sense to use `SequenceOfCorrespondences` here, because there is also e.g. `SequenceOfOMS`, and in the future, there could be more. Should we introduce a class `Sequence`?

**Comment by fabianneuhaus** [comment]
This sounds good to me. (If it leads to problems, we also could leave domain and range just undeclared.)

**Comment by tillmo** [comment]
OK, see 337_sequence_of_correspondences of the DOL ontology repo.
Text for FTF: SequenceOfCorrespondences is actually used in Alignment, we have corrected this and also introduced a class Sequence serving as domain/range of object properties hasSequenceMember and isSequenceMemberOf.

**Comment by fabianneuhaus** [comment]
OMG proposal added
