### ISSUE TITLE
transformation tool conformance insufficient

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#339]
It says “a transformation tool is DOL-conformant if it implements one (or more) language translations, logic translations, language projections and/or logic projections.” There must surely also be some DOL-related requirement here, e.g. that the tool consumes and produces DOL-conforming documents.

see http://issues.omg.org/browse/DOL-36

**Comment by fabianneuhaus** [comment]
Proposal:  “a transformation tool is DOL-conformant if it is a DOL Parser and implements one (or more) language translations, logic translations, language projections and/or logic projections.”

**Comment by tillmo** [comment]
I would not say that a transformation tool **is** a DOL parser. It may use one, or it even may use none and operate on the DOL abstract syntax (this is the preferred way, I think). Then, only a parser for the DOL abstract syntax is needed, but this should not be called a DOL parser.

My suggestion: “a transformation tool is DOL-conformant if it operates on DOL (abstract) syntax and implements one (or more) language translations, logic translations, language projections and/or logic projections.”

**Comment by tillmo** [comment]
see 339_transformation_tool_conformance
Text for DOL FTF: we have added that a transformation tool has to operate on the DOL (abstract) syntax.

**Comment by fabianneuhaus** [comment]
omg proposal added
