### ISSUE TITLE
Inaccurate footnote 35

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#343]
Footnote 35 says "there does not seem to be default in UML 2.5". This is incorrect. UML 2.5 specifies the defaults in the Classifier description of MultiplicityElement thus:

isOrdered : Boolean [1..1] = false

isUnique : Boolean [1..1] = true

see http://issues.omg.org/browse/DOL-40

**Comment by AlexanderKnapp** [comment]
Yes, you're perfectly right - changed the footnote.

**Comment by AlexanderKnapp** [comment]
I cannot log in to the OMG DOL issue database, but I've opened a branch issue-343.

**Comment by tillmo** [comment]
thanks! Then we can close this here.

**Comment by fabianneuhaus** [comment]
OMG proposal generated
