### ISSUE TITLE
Mention that minimize can be used to express reachability models

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#348]
If applied to algebraic signatures (sorts + operation symbols), minimize can be used to express reachability (i.e. term-generatedness) of first-order models.

**Comment by tillmo** [comment]
see 348_reachability
Text for FTF: we added a footnote mentioning the use use minimize for expressing term-generatedness, and provided some datatype example (and corrected some other datatype example)

**Comment by fabianneuhaus** [comment]
OMG proposal added

**Comment by fabianneuhaus** [comment]
see issue
http://issues.omg.org/browse/DOL-90
