### ISSUE TITLE
LaTeX problem with TeXLive 2016

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#349]
```
[116]
! Undefined control sequence.
\pgfmath@dimen@ ...men@@ #1=0.0pt\relax \pgfmath@ 
                                                  
l.10296 ..., pos2=2.7, geometry=|-|]{Net}{Station}
```
This does not happen with TeXLive 2015.

I have pushed a workaround in 7f584ed0. So please use 6b3211de as basis to debug this issue.

**Comment by AlexanderKnapp** [comment]
An update to tikz-uml 1.0 resolves this issue. I've pushed the new version
onto issue-343.

Am 01.08.2017 18:44 schrieb "Till Mossakowski" <notifications@github.com>:

**Comment by tillmo** [comment]
good, many thanks!
