### ISSUE TITLE
Inconsistent white space before *  in grammar

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#350]
See page 52, sometimes it says "Symbol*" and sometimes "Symbol *". This should be consistent.

**Comment by fabianneuhaus** [comment]
There are actually parenthesis in the Latex code -- which are ignored because they are declared as escape characters.

**Comment by fabianneuhaus** [comment]
@tillmo Could you generate a diff for the changes in branch 350-Inconsistent-White-Space?

**Comment by tillmo** [comment]
it seems to be very difficult to generate the diff. Can we just silently change this? After all, it is just a space...

**Comment by fabianneuhaus** [comment]
unfortunately, what I first thought was a whitespace, was really errors in the concrete grammar
there were missing parenthesis in the EBNF

**Comment by fabianneuhaus** [comment]
example, the text read A , B * 
and what was meant was (A , B )*
the parenthesis were missing because latex treated the parenthesis as escape characters in the lstlisting environment.

**Comment by tillmo** [comment]
it is very difficult to create a diff because the source text is pratically identical (except from the declaration of the escape characters)

**Comment by fabianneuhaus** [comment]
can you create a diff on the pdf level? all differences will affect EBNF grammars

**Comment by tillmo** [comment]
I have an idea. Can try this tomorrow morning, have to leave now...

**Comment by tillmo** [comment]
diff is checked in now, uff.

**Comment by fabianneuhaus** [comment]
issue opened http://issues.omg.org/browse/DOL-92

**Comment by fabianneuhaus** [comment]
omg proposal added
