### ISSUE TITLE
BasicOMS need to be included in delimiters 

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#351]
we have 
OMS = ... | OMS OMSTranslation | ...
OMSTranslation = ... |  ’with’ LanguageTranslation+

Assuming our OMS language contains an opitonal syntax element 'with' IRI, we could have something like 

ontology foo = 
... 
with <www.example.com>

this would be ambiguous, since it would not be clear whether the "with <www.example.com>" would be part of the basic OMS or not.

**Comment by tillmo** [comment]
Since `with` is a keyword (see 9.8.1), this is always considered to be DOL structuring. If a basic OMS contains a DOL keyword, it must be closed in curly braces. I think the latter rule has been implemented in Hets, but is missing in the standard.

**Comment by tillmo** [comment]
see 351_basic_OMS_delimiters
Text for FTF: we have added the restriction that inside DOL documents, a Basic OMS must not use any DOL keywords, unless it is enclosed in curly braces.

**Comment by fabianneuhaus** [comment]
Please have a look at the diff file. I am pretty sure some form of delimiters have been lost between the quotation marks. This may be related to the escape character problem in issue #350

**Comment by tillmo** [comment]
OK,fixed.

**Comment by fabianneuhaus** [comment]
dol issue created
http://issues.omg.org/browse/DOL-94

**Comment by fabianneuhaus** [comment]
omg proposal added
