### ISSUE TITLE
page 64, 65 -- diff does not show the new version of the file

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#369]
The newly formatted keyword list ist not shown in the diff file.

**Comment by tillmo** [comment]
which DOL issue was that?
I remember that I have tried to mark this as in the other cases, but it has been very difficult and I gave up. Could we perhaps introduce a "diff note" (as I have done in two other places) stating that just the formatting has changed?

**Comment by tillmo** [comment]
OK, I found a way of properly doing it, see efe3d4c0827bd4d06e5f1437c157c09af0cff4c5. I marked it as DOL-37, is this correct?

**Comment by fabianneuhaus** [comment]
this was not a OMG issue. I would claim that formatting does not belong to the issues that we need link to a OMG issue. The same is true for changes on the title page (e.g., changing the date.)

**Comment by fabianneuhaus** [comment]
I don't think that you even need to highlight this kind of formatting change as a change. I was just puzzled that it appeared in the diff still as in the  original version (as long list)

**Comment by tillmo** [comment]
so I will remove the hightlighting again...
