### ISSUE TITLE
add mereology example in 8.7

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#37]

**Comment by gruninger** [comment]
What exactly is the purpose of this mereology example? Mereologies are logically synonymous with partial orderings, which are not definable in OWL2; as a result, the example cannot illustrate logic mappings. Do we show how we can use DOL to specify the mapping between a particular axiomatization of mereology and the corresponding partial ordering?

**Comment by tillmo** [comment]
the section is about mappings in general, so an example could also bring a mapping between two Common Logic ontologies. Any such mapping (preferably a simply one) would be welcome.
