### ISSUE TITLE
new \nrefs are confusing

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#372]
To give an example in section D.1 it says 
"The metaclass Text NR24, 12.2 is a subclass [...]"
This is confusing, because it seems that the metaclass is called "Text NR24". 
Surely this is supposed to be a citation. It should say something like 
"The metaclass Text (see NR24, section 12.2)  is a subclass [...]"

The same is true for the new \nrefs in section C.2. 
It may have happened in other places.

**Comment by fabianneuhaus** [comment]
I found additional in sections 6.1, E.1, F2, F3, G2, H2

**Comment by tillmo** [comment]
This is not new. There are dozens of old \nrefs used in the same way, for example, 4.8. Do we really want to change all these? (would be quite some effort)

**Comment by fabianneuhaus** [comment]
there is a qualitative difference between the way the \nrefs were used previously and these new occurrences. In previous uses (at least the vast majority of them) the \nrefs were clearly marked as references to documents. Often by the context, sometimes explicitly (e.g., see section x of \nref). The examples above disrupt the text and make them unreadable.
