### ISSUE TITLE
improve Annex (informative): Extended Logic Graph

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#57]

**Comment by tillmo** [comment]
since now both annexes are informative, maybe we can merge the core logic graph and the extended logic graph? Or do we want to keep the core logic graph, because it contains the languages listed in the RFP?

**Comment by okutz** [comment]
I think it is useful to have the core graph for the normative part. It is also also much simpler to look at and understand. I would keep it.

**Comment by tillmo** [comment]
OK, but still the core graph is informative only

**Comment by tillmo** [comment]
please update figure I.1 in the same way as fig. H.1

**Comment by tillmo** [comment]
please also change "sublogique" into "sublogic"
