### ISSUE TITLE
add examples for each use case in chapter 7

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#65]

**Comment by mcodescu** [comment]
there are some examples there, but in the other cases (PROV, metadata, UML) I'm afraid I can't do much.

**Comment by tillmo** [comment]
We have now examples for Onto-1,2,3, Spec-1,2 and Model-1,2,3. Examples for Onto-4,5 are missing. Either someone comes up with examples for these, or we should omit these use cases.

**Comment by tillmo** [comment]
we decided to keep Onto-4,5 without DOL text
