### ISSUE TITLE
ontoiop.org still points to old Ontolog wiki

### ISSUE THREAD

**Issue by clange** [tillmo/DOL#66]
The old Ontolog wiki is frozen. Can you please point ontoiop.org to http://ontolog-02.cim3.net/wiki/OntoIOp ?

**Comment by tillmo** [comment]
@clange, are you still working on this? The easiest way would be just to copy the old wiki page at http://ontolog.cim3.net/cgi-bin/wiki.pl?OntoIOp

**Comment by clange** [comment]
I once had the good intention to work on it; however I was too busy with other things :-(

**Comment by tillmo** [comment]
maybe then we should just copy it?

**Comment by tillmo** [comment]
have copied it, and redirected to new wiki
