### ISSUE TITLE
Add MOF  as example for DOL compliant language

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#76]
shows the use of DOL for modelling languages

**Comment by tillmo** [comment]
@AlexanderKnapp, do you think we just could refer to the UML class diagram institution and reuse it as a MOF instiution? After all, MOF is very similar to class diagrams.

**Comment by tillmo** [comment]
@AlexanderKnapp, I have assigned this issue to you - an answer to the above question probably would suffice.

**Comment by AlexanderKnapp** [comment]
At least Essential MOF should be covered by our institution. For Complete MOF some things would have to be added, I guess.

**Comment by tillmo** [comment]
good, I have now added as annex F:
Since essential MOF (EMOF) is a sublanguage of UML class diagrams,
we can define a corresponding institution that is a subinstitution
of that for UML class diagrams (see annex~\ref{a:uml-class}).
