### ISSUE TITLE
throw bridges out? - better form of bridges and E-connections

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#83]
Now that we have contextualized semantics of alignments, it seems that we do not need bridges anymore. Do you agree?

**Comment by tillmo** [comment]
for now, I have removed bridges, because in the present form they were just translations along a logic mapping. If you want to have a new form of bridges, please make a proposal.

**Comment by okutz** [comment]
should be re-considered for next revision when we have published the theory behind alignements etc
