### ISSUE TITLE
CURIEs may contain commas, colons, semicolons, parenthesis and the equal sign 

### ISSUE THREAD

**Issue by cmaeder** [tillmo/DOL#87]
The concrete grammar contains comma-separated lists (apart from space-separated lists) of IRIs: SymbolItems, SymbolMapItems, RefMap (via NodeMap), AlignDefn,  CorrespondenceBlock (via Correspondence), ResultDefn, Vars

If commas are not forbidden in CURIEs they should not be used to separate items! "a, b" reads "a," as single CURIE and even "a , b" requires to know if an IRI list is separated by commas or by spaces (yielding three names in the latter case). 

```
ImportName           = '%(' , IRI , ')%' ;
ExtensionName        = '%(' , IRI , ')%' ;
```

Since ")" may be part of an IRI, is a space required before ")%"? (In hets "%(" starts a comment that is part of the lexical rules. )

Also "=" and ":" usually need to be surrounded by spaces. ";" is not a keyword in DOL so a legal IRI.

**Comment by gnn** [comment]
The commit above commit and the amendments 083973fa10c8adf5a14ffa6133d24e8a10028477 and 2375cb69aa6eaa6ff6da36cdcd41fa9c0adbaffa should fix this. Should disallowing commas in the reference part of CURIEs not be enough to fix the issue, please reopen.
