### ISSUE TITLE
finalize abstract and concrete syntax

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#9]
* have a look whether the two syntaxes match 
* review the syntaxes for uniform style

**Comment by tillmo** [comment]
@mcodescu: I have now eliminated almost all TODOs. Please have a look.

**Comment by mcodescu** [comment]
I have made a thorough check and I made some minor changes myself. What is left:
  - PrefixMap and the related non-terminal appear in different subsections in the abstract syntax (AS) and concrete syntax (CS). It would improve readability to have them in same place.
  - is there a reason to want to have a non-terminal for the network keyword?
  - in CS, BasicOMSinConformingLanguage is missing the 'Basic' 
  - in CS, ExtendingOMS has as a case OMS, Extraction, which is not reflected in the AS
  - ExtensionOMS is missing in the AS, which makes impossible to write SP then %cons SP'...
  - GroupOMS is missing in the AS
  - Extraction and Approximation make use of QualInterfaceSignature, which has in the AS the alternatives keep signature and remove signature. In the CS we have forget/keep and select/reject and no non-terminal for QualInterfaceSignature. Is this intended or is this a mistake?
  - in the AS there is a non-terminal for MonoDef which does not have a match in the CS. Either remove the non-terminal in AS, or add a correspondent in CS. Same goes for Implied
  -  consistent and inconsistent are missing in the AS
  -

**Comment by tillmo** [comment]
I have addressed all the points. Sometimes, the AS deviates deliberately from the AS (cf. items 6,7 and 9).
