### ISSUE TITLE
EquivType is ambiguous

### ISSUE THREAD

**Issue by cmaeder** [tillmo/DOL#95]
```
EquivType            = GroupOMS , '<->' , GroupOMS , '=' , OMS
                     | NetworkName , '<->' , NetworkName , '=' , Network ;
```

The parser can not distinguish between OMS and Network following `'='`

**Comment by tillmo** [comment]
OK, but the parser could assume an OMS, and during static analysis, replace this with Network, if necessary. I think Hets already does such kind of things.
