### ISSUE TITLE
Merge API4KBs ontology and LoLa to something standard-conforming

### ISSUE THREAD

**Issue by clange** [tillmo/DOL#97]
@ElisaKendall, @greenTara FYI

* merge ontologies (target: https://ontohub.org/meta/lola/ontology/)
 * API4KBs OntoIOp terminology: https://github.com/API4KBs/api4kbs/blob/master/ontologies/OntoIOpTerminology.rdf
 * LoLa latest version: https://github.com/ontohub/OOR_Ontohub_API/blob/master/lola/ontology/dol-rdf.omn
* while doing so, take care of technical limitations
 * e.g. Protégé doesn't like functional properties to be part of property chain axioms
 * e.g. certain things in LoLa (e.g. relationships between classes representing types of translations, and the corresponding properties) go beyond the expressivity of OWL
* throw out things that aren't part of the standard (such as "state of standardization")
* keep some things that we can realistically _add_ to the standard (such as "types of logic translations")
* make sure all terminology is consistent with the OntoIOp Standard
* make sure all concepts/roles/etc. and the ontology top level have the metadata required by OMG (OMV etc.)

How to publish it:
* official version will be published under its canonical URI = URL
 * Ontology IRI = http://www.omg.org/spec/OntoIOp/OntoIOpTerminology/ (may change to DOL)
 * version IRI = http://www.omg.org/spec/OntoIOp/20150501/OntoIOpTerminology/ (date may change)
* "see also" metadata will point to the metadata Ontohub repository where the latest version is under development

**Comment by greenTara** [comment]
Christoph - this seems like a correct statement of the issue. Thanks for 
taking this on.

Tara

**Comment by clange** [comment]
@tillmo, @gabrielcc2 did you come up with anything that I could proof-read and/or use as input for my tasks #90 and #91?

**Comment by gabrielcc2** [comment]
Hi, I submitted a version of this matching to Prof. Mossakowski last week. I think that it must still be in review.

**Comment by tillmo** [comment]
@gabrielcc2, yes, got it - many thanks! I have forwarded it to @clange

**Comment by tillmo** [comment]
see https://ontohub.org/meta/lola/ontology/lola.omn
