### ISSUE TITLE
add precedences of operators

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#99]
see the CASL reference manual for some initial suggestion

**Comment by gnn** [comment]
I couldn't do this so far because figuring out which keywords are operators and which of those need disambiguation by precedence as they can appear in the same context takes a lot of time for me. I'm still trying though.

**Comment by gnn** [comment]
I addressed this in commit #be99c66. I'm requesting a review from someone more knowledgeable in the DOL syntax than me. The commit message of #be99c66 might be of help and to see the text just search for 'precedence' in the PDF.

**Comment by tillmo** [comment]
looks fine. I just have added minimize and free.
